## **Acknowledgments**
***

<!--
Fill in any Acknowledgments using an example from a previous case study if needed: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Acknowledgments
-->

We would like to acknowledge Candace Savonen, Casey Greene, Emma Lathouwers, and Taylor Reiter for their expert review of this case study. 

We would also like to acknowledge the National Institute of General Medical Sciences for funding this work (1R25GM160622).

Icons are from [iconpacks](https://www.iconpacks.net/).

Avatars are from [avataaars](https://getavataaars.com)

### AI Attribution Statement

The text in this work was primarily human-created. AI was used to make content edits, such as changes to scope, information, and ideas. AI was prompted for its contributions, or AI assistance was enabled. AI-generated content was reviewed and approved. The following model(s) or application(s) were used: Microsoft 356 Copilot (GPT-5).

AIA Primarily human, Content edits, Human-initiated, Reviewed, Microsoft 356 Copilot (GPT-5) v1.0

The code for the drag-and-drop activity was entirely AI-generated. AI was prompted for its contributions, or AI assistance was enabled. AI-generated content was reviewed and approved. The following model(s) or application(s) were used: Microsoft 356 Copilot (GPT-5).

AIA Entirely AI, Human-initiated, Reviewed, Microsoft 356 Copilot (GPT-5) v1.0

More information about this AI attribution can be found [here](https://aiattribution.github.io).

