# **Additional Information**
***

<!--
Use this section to provide any additional information or resources on the topic and methods covered in the case study
-->

## **Helpful Links**
***

[These are a set of resources that I've identified or reviewers have identified. I will link to some of these resources in relevant parts of the lesson (so that each element of GitHub includes a resource of where to learn more). I will also reorganize these resources here to group similar resources together.]

- [happy git with R](https://happygitwithr.com): online book that covers most relevant topics for using Git and GitHub with R
- [How to Use Git/GitHub with R](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r): blog post about getting Git and GitHub set up and working with RStudio. This uses the built-in Git GUI in RStudio instead of GitHub Desktop
- [Dangit, Git!?!](https://dangitgit.com/en): brief description of some common Git errors and how to resolve them
- [Intro to reproducibility in cancer informatics](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/): short course on reproducibility for scientific projects, includes Git and GitHub in chapter 4 and provides other resources on reproducibility
- [Advanced reproducibility in cancer informatics](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/): short course on more advanced reproducibility for scientific projects, includes GitHub in chapter 3 and provides other resources on reproducibility
- [Carpentries](https://carpentries.org):
  - [Install Git](https://carpentries.github.io/workshop-template/install_instructions/): instructions on installing Git (and other types of software)
  - [Set up Git](https://swcarpentry.github.io/git-novice/02-setup.html): instructions on setting up Git
  - [Build on existing branch](https://docs.carpentries.org/resources/curriculum/fetch-existing-branch.html): instructions on how to work from a branch on someone else's fork of a repository 
- [Hands on introduction to Git and GitHub](https://training.arcadiascience.com/workshops/20220920-intro-to-git-and-github/lesson/): another introduction to Git and GitHub, covering some overlapping material and some additional material
- [Contributing to Galaxy Training Network with GitHub](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/github-contribution/tutorial.html): tutorial on how to contribute to an open source project with GitHub
- [GitHub cheatsheet](https://education.github.com/git-cheat-sheet-education.pdf): cheatsheet with Git commands that can be used in the command line

<u>Terms and concepts covered:</u>

<u>Packages used in this case study: </u>

<!--
Automatically include the packages table from _packages.qmd?
-->

***
