<!--
List any important bioethics considerations when performing an analysis like this or working with data like this.

See doi: 10.1007/s41649-019-00099-x and https://depts.washington.edu/bhdept/ethics-medicine/bioethics-topics/articles/principles-bioethics for principles and considerations.
Examples may include: how identifiable (or re-identifiable) is your data? cell lines or consent? specific considerations for a specific population?
-->


# **Ethical Considerations**
***

There are some important ethical considerations when working with version control, as well as with health related data in general and when collaborating on scientific projects. 

1. When hosting data, code, and results on {{< glossary "GitHub" >}}, **make sure to never include personally identifiable information (PII) or protected health information (PHI) in a repository** (even private repositories are not secure enough for sensitive data). This includes names, dates of birth, medical records and diagnosis, lab results, identifiable genomic sequencing data, as well as other types of data. You can read more about PII and PHI in [this course](https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-privacy.html#pii-personal-identifiable-information) about ethical data handling. For more general information about data management, you can explore [this course](https://hutchdatascience.org/Proactive_Data_Management_and_Sharing/). 

    a. If you do commit sensitive information to a version controlled repository on GitHub, it is **not sufficient to simply remove the file, commit the changes, and push again**. If you do this, any files with sensitive information will be part of a commit, and will therefore be a part of the history of the repository. While there are ways to remove sensitive information from a local commit, and from a GitHub repository, these are more complicated operations and will affect collaborators that work on the repository with you. It is important to inform collaborators of the sensitive information that has been committed.
  
1. If passwords, access tokens, API keys, or other credentials are accidentally committed and pushed to a remote repository on GitHub (either public or private), they should be considered compromised and changed as soon as possible, and all collaborators who work with that repository should be alerted.   
  
1. Make sure to keep comprehensive documentation for scientific projects to avoid losing track of which data generated a set of results or figure, or which version of a software that you used in an analysis. Reproducible science is ethical science: without a transparent and well-documented process, others in the scientific community cannot easily verify or trust your results.
1. For projects with large teams, it can be challenging to track individual contributions. {{< glossary "Version control" >}} histories can be helpful to see who worked on each component on an analysis, in order to fairly acknowledge each contributor’s work. You can read [this paper](https://link.springer.com/article/10.1007/s11948-014-9562-8) for more ethical considerations related to large team science. 
1. When performing a {{< glossary "meta-analysis" >}} such as the one described in this case study, it is important to be transparent about inclusion and exclusion criteria for studies and for individual observations within studies. Criteria should be determined before analysis, to avoid choosing studies that will support a desired conclusion. It is also important to properly cite the original studies and recognize the groups that collected the data. 

***

<!--
Consider incorporating a checklist of statements that learners should answer/discuss for every case study for bioethics principles.
-->
