<!--
More details on the background on the case study topic as well its relation to biomedical science.
Videos or images may be helpful so this includes an example of embedding a video.
-->

# **Context**
***

### What is a microbiome?

A microbiome is a collection of microorganisms that live in an environment. One commonly studied microbiome is the human gut microbiome. The bacteria that live in our gut help regulate our metabolism, digest fiber, protect us against pathogens, and perform other important roles in our [health](https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2026.1785607/full). Studies have shown associations between changes to the gut microbiome and many diseases, including diabetes, autoimmune diseases, and Alzheimer's disease. 

[add image?]

Much of the gut microbiome composition is determined at birth and in early life, and the infant gut microbiome has implications for health later in [life](https://www.tandfonline.com/doi/full/10.1080/19490976.2021.1911571#d1e318). Therefore, scientists are interested in understanding more about the factors that shape the infant gut microbiome. One question of interest is how similar the gut microbiomes are between infants and their mothers, and how this changes over time. In order to address this question, several longitudinal studies have been conducted to collect samples from pairs of infant and mother longitudinally. Processing microbiome samples is expensive, and therefore each study is limited in the number of samples they can collect. Want et al. conducted a meta-analysis of eight of these studies, using this large data set to compare gut microbiome composition and metabolic function between infants and mothers, as well as investigate other related questions.

### What is a meta-analysis?

https://www.sciencedirect.com/science/article/pii/0197245686900462?via%3Dihub

A meta-analysis is the analysis of data from a collection of studies targetting a common research question. Ideally these studies would have similar participants and protocols. A meta-analysis may be beneficial when the original studies have samples sizes that are too small to provide enough evidence for significant results. Additionally, meta-analyses provide opportunities to utilize data, which often require a large amount of effort and funding to collect, in a new way. Meta-analysis can also provide an approach to generate a consensus result from a set of studies. However, meta-analyses must be conducted with care, as combining data from studies with different participant populations and different study designs can lead to misleading results. 

https://www.psychiatrist.com/jcp/primer-on-individual-participant-data-meta-analysis-strengths-limitations/
https://pmc.ncbi.nlm.nih.gov/articles/PMC6993967/ 

There are two general approaches to performing meta-analyses. In the first approach, estimates or other summaries from each study are combined in order to generate a summary from the set of studies. Benefits of this approach include that the original data from each study are not needed. However, original studies can only be combined if they estimate the same summary of their population (for example, a difference in means between two groups or an odds ratio). Additionally, the data would need to be analyzed in the same way for each study (for example, the same covariates would need to be adjusted for). In the second approach, data from each of the studies are combined and re-analyzed jointly, accounting for the study from which each observation originated. A benefit of this approach is that new research questions can be asked, as long as the relevant data exist from each study. However, it can be more time-consuming and requires accessing the raw data from each study. 

Wang et al. take the second approach, by using the raw study from eight longitudinal studies of infant and mother gut microbiomes, and processing it with a unified protocol. When they fit models to the data, they "block" by study, which means they include a term in their models that accounts for which study each participant came from, so that results are not confounded by differences between study cohorts. However, the validity of this approach depends on how comparable the original studies are. While Wang et al. account for study effects in their analysis, they do not extensively characterize the study cohorts before pooling them. In particular, differences in sample size and longitudinal sampling schedules may affect the interpretation of results. This motivates the question that we explore in this case study. Specifically, we want to understand how comparable these studies are, both in terms of sample size, and in terms of when they performed their longitudinal sampling on infants and mothers. 
  
***
