<!--
Update the file paths as needed throughout
-->

<!--
At the end of this section, save incremental data so that users can pause and come back later
-->

# **Data Import**
***

Now that you have created this GitHub repository, and have tracked this project locally with Git, you can start working on the study comparison in R. Open RStudio to your project "infant_gut_analysis". We will start by taking a look at the data. To understand the data contained in this project, first see what the README tells you. 

Start by opening the file that reads in the raw data and running it. Look at the output. How many observations are included in our data set? How many variables are included in our data set? 

^ add question box for this! 

<details> <summary> Hint </summary>

Data is imported in the file "01_pull_study_data.R". You can find out how many rows are in a data frame with the function `nrow(name_of_data_frame)`. You can see the variables in a data frame with the function `names(name_of_data_frame)`.

</details>

***
