<!--
Don't adjust the shortcode or the table header in this file, only the markdown table contents
-->

## **Main Questions Revisited**

::: {.callout-note collapse="true" title="Main Questions Revisited: What Did We Learn"}


| Question                                    | Current answer                                     | Caveat                                |
| :------------------------------------------ | :------------------------------------------------- |:------------------------------------- |
| How does the use of version control contribute to transparent and reproducible science? | As we describe in the [introduction to Git and GitHub section](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github), version control provides a full history of a project, showing who made which changes and when. Additionally, commit messages and pull request descriptions explain why changes were made. Version control also provides an easy way to make a public online code repository for a project. | Versions of a project are only tracked when the user manually makes a commit, changes are not automatically tracked. Commit messages and pull request descriptions are only useful when they are concise and meaningful. |
| How can Git and GitHub be used to facilitate collaboration on a research project? | GitHub provides a central location to store the files for a project, and collaborators can pull changes to their local repository, make updates, and push changes back to the remote repository. An individual can suggest a series of changes through a pull request (see the [pull request section](https://www.opencasestudies.org/ocs-bio-version-control/#pull-requests) for more information), and request a code review from a collaborator before merging the changes into the main branch of the repository. | It is important for collaborators to pull before they begin work locally, otherwise they will likely create merge conflicts (see the [troubleshooting section](https://www.opencasestudies.org/ocs-bio-version-control/#troubleshooting-git-and-github) for advice for working through merge conflicts). The careful use of branches will let collaborators work on different aspects of projects at different times and help organize work to be reviewed in pull requests. More information about branches can be found in the [branches section](https://www.opencasestudies.org/ocs-bio-version-control/#branches).|
| In this meta-analysis of infant git microbiome samples, how do the original studies compare in their sampling designs? | From the plots created in the [data visualization section](https://www.opencasestudies.org/ocs-bio-version-control/#data_visualization), we can identify major differences across studies in terms of number of samples, proportion of samples from infants versus mothers, and different times at which samples were collected from infants and from mothers. | As described in the [limitations section](https://www.opencasestudies.org/ocs-bio-version-control/#limitations), the sampling date is measured differently in different studies, and there are other potentially relevant study characteristics that we don't consider in this analysis. |


:::

***
