# **Packages and Setup**
***

Before we get into the coding, we want to describe the R packages that we'll use in this case study, or that are used in other scripts contained in our repository:

```{r, message = FALSE, warning = FALSE, echo = FALSE}
library(here)
library(readxl)
library(dplyr)
library(ggplot2)
library(stringr)
```

Package    | Use | Where this packages is used  
---------- |------------- | ----------------------------
[here](https://here.r-lib.org) | To construct file paths within folders | [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)
[readxl](https://readxl.tidyverse.org){target="_blank"}      | To read excel files into R | [Data import](https://www.opencasestudies.org/ocs-bio-version-control/#data-import)
[dplyr](https://dplyr.tidyverse.org){target="_blank"}      | To combine and manipulate data tables | [Data import](https://www.opencasestudies.org/ocs-bio-version-control/#data-import), [Data wrangling](https://www.opencasestudies.org/ocs-bio-version-control/#data-wrangling), [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)
[ggplot2](https://ggplot2.tidyverse.org) | To visualize data | [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)
[stringr](https://stringr.tidyverse.org) | To manipulate strings | [Data wrangling](https://www.opencasestudies.org/ocs-bio-version-control/#data-wrangling)


The first time we use a function, we will use the `::` to indicate which package we are using. Unless we have overlapping function names, this is not necessary, but we will include it here to be informative about where the functions we will use come from.

Three of these packages, `dplyr`, `ggplot2`, and `stringr` are part of the [tidyverse suite of packages](https://tidyverse.org). The `tidyverse` includes eight packages that can easily be used together and share data structures and syntax. While each of the packages can be installed or loaded separately (as we do above), they can be installed or loaded all at once using `install.packages("tidyverse")` or `library(tidyverse)`. 
