{
  "hash": "9d78b9b7c23365a139606ff1f8f8ec07",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"**Biomedical Open Case Studies: Making version controlled reproducible analyses**\"\nbibliography: resources/references.bib\ninclude-sections:\n  stat-los: false\n  lo-map: true\n  data-import: true\n  data-exploration: false\n  data-wrangling: true\n  data-viz: true\n  data-analysis: true\n  main-q-table: true\n---\n\n<!--\n  Update above to exclude optional or new sections by changing from true to false.\n  Update the various qmd documents below with each component of a Bio-OCS case study.\n  Besides filling in the title in the header of this document, no other changes should be necessary within this file.\n  Use the `include-sections` within the header to toggle section inclusion/exclusion as needed.\n  For documentation on quarto syntax possibilities, use https://quarto.org/docs/authoring/markdown-basics.html.\n  Examples in the documentation range from including images and videos to including margin notes, annotating code, and linking within a document.\n-->\n\n\n\n:::{.outline }\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f9c5fef626_0_3.png){fig-align='center' fig-alt='Motivation for using version control' width=1250}\n:::\n:::\n\n:::\n\n\n\n\n<!--\nThe disclaimer block, license block, and funding info generally will not need updated\n\nPlease update the access information (e.g., github link and data access)\nas well as any system or server requirements to work with the data\n-->\n\n:::{.disclaimer_box}\n::::{.disclaimer_box_header}\nDisclaimer\n::::\n::::{.inner_block}\nThis case study is still getting reviewed by a team of experts. While it is complete and has undergone some review by experts, we are continuing to improve the case study. If you have any suggestions, please email us at bioOCS@fredhutch.org. This case study is scheduled to be finalized by October 19, 2026.\n::::\n:::\n\n::: {.panel-tabset .frontmatter-tabs}\n\n#### Disclaimer\n\n::::{.disclaimer_box}\n:::::{.disclaimer_box_header}\nDisclaimer\n:::::\n:::::{.inner_block}\nThe purpose of the [Open Case Studies](https://opencasestudies.github.io){target=\"_blank\"} project is **to demonstrate the use of various data science methods, tools, and software in the context of messy, real-world data**. A given case study does not cover all aspects of the research process, is not claiming to be the most appropriate way to analyze a given data set, and should not be used in the context of making policy or clinical decisions without external consultation from scientific experts or medical care professionals. In addition, due to size constraints, datasets used within a case study may be a subset of the original/full dataset.\n:::::\n::::\n\n#### License \n\n::::{.license_box}\n:::::{.license_box_header}\nLicense information\n:::::\n:::::{.inner_block}\nThis work is licensed under the Creative Commons Attribution-NonCommercial 4.0 [(CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/deed.en){target=\"_blank\"}  United States License unless otherwise noted.\n:::::\n::::\n\n#### Funding\n\n::::{.funding_box}\n:::::{.funding_box_header}\nFunding information\n:::::\n:::::{.inner_block}\nThis work is funded through the National Institutes of Health, specifically the National Institute of General Medical Sciences: Grant Number 1R25GM160622.\n:::::\n::::\n\n#### Citation\n\n<!--\nThe reference block (specifically the inner_block) should be updated to reflect how this case study should be cited\n-->\n\n:::{.reference_box}\n::::{.reference_box_header}\nTo cite this case study, please use:\n::::\n::::{.inner_block}\nTeichman, Sarah and Wright, Carrie. (2026). [https://github.com/opencasestudies/ocs-bio-version-control/](https://github.com/opencasestudies/ocs-bio-version-control/). Making version-controlled reproducible analyses (Version v1.0.0).\n::::\n:::\n\n\n\n#### GitHub Repository \n\n<!--\nUPDATE: ACCESS Information (github source and data)\nIn this space, provide an open access link to the case study source files.\nThis is necessary for users to get access to case study data, at a minimum.\nSee the following example from a previous case study (prior to Motivation section): https://www.opencasestudies.org/ocs-bp-co2-emissions/\n-->\n::::{.github_repo_box}\n:::::{.github_repo_box_header}\nGitHub Repository\n:::::\n:::::{.inner_block}\nTo access the GitHub repository for this case study see here: [https://github.com/opencasestudies/ocs-bio-version-control](https://github.com/opencasestudies/ocs-bio-version-control)\n:::::\n::::\n\n<!--\nIf the data isn't in the main github repository, be sure to describe and link to the open source location of the data and how to access it\n-->\n\n#### Keywords\n\n::::{.keyword_box}\n:::::{.keyword_box_header}\nKeywords\n:::::\n:::::{.inner_block}\n\n* version control\n* Git\n* GitHub\n* reproducibility\n* meta-analysis\n* infant gut microbiome\n\n:::::\n::::\n\n\n<!--\nInclude bioOCSdata package information once ready/applicable\n-->\n:::\n\n## Prerequisites\n\n***\n\n:::{.prereq_box}\n::::{.prereq_box_header}\nPrerequisites\n::::\n::::{.inner_block}\nTo follow along with this case study, you'll need the following installed:\n\n- R ([install here](https://www.r-project.org))\n- RStudio ([install here](https://posit.co/download/rstudio-desktop)) or Positron ([install here](https://positron.posit.co/install.html)) or another IDE compatible with R\n\nIt will also be helpful to be have the following skills:\n\n- basic R skills (many introductory courses can be found online, including [this one](https://hutchdatascience.org/Intro_to_R/))\n- familiarity with `dplyr` and `ggplot2`, or willingness to learn (these [`dplyr`](https://rstudio.github.io/cheatsheets/data-transformation.pdf) and [`ggplot2`](https://rstudio.github.io/cheatsheets/data-visualization.pdf) cheatsheets may be helpful, as well as the original [open case studies](https://www.opencasestudies.org/search.html))\n- OPTIONAL: command line skills (this [resource for basics with the command line](https://swcarpentry.github.io/shell-novice/key-points.html) maybe helpful)\n  - this is not necessary if using GitHub Desktop, as is suggested in this case study, however there are alternate instructions throughout the case study that use the command line to interact with Git\n\nYou do not need to have any previous Git and GitHub knowledge or experience for this case study. \n::::\n:::\n\n***\n\n\n\n\n<!--\nDescribe the biological motivation for this case study.\nInclude relevant explanatory images and references throughout.\nSee this previous case study as an example: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Motivation\nImages or videos may be helpful so this includes an example of including an image.\n-->\n\n# **Motivation**\n***\n\nIn this case study, we ask you to imagine that you are working with a collaborator on a scientific project. You receive the following email, with a request for your help performing a preliminary data analysis. Don't worry if you don't understand the context of this analysis right now, background will be given later in the case study. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3d9461be06f_0_0.png){fig-alt='Motivation email asking for cohort comparison analysis' width=100%}\n:::\n:::\n\n\nIf you were to start working on this project with your collaborator, it may look something like this.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e1f8f72664_0_368.png){fig-alt='Back and forth over email without version control' width=100%}\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e1f8f72664_0_429.png){fig-alt='Back and forth over email without version control' width=100%}\n:::\n:::\n\n\n\nBetween your own edits as you work on this project and the back-and-forth with your collaborator, it will quickly become challenging to keep track of all of the files and changes to them over time. A solution to this is {{< glossary \"version control\" >}}! \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e1f8f72664_0_444.png){fig-alt='Back and forth over email without version control' width=100%}\n:::\n:::\n\n\nIn this case study, you will learn how to use {{< glossary \"Git\" >}} and {{< glossary \"GitHub\" >}} to track this project and perform the requested comparison of studies used in the {{< glossary \"meta-analysis\" >}}. You will also learn how version control can facilitate collaboration and make a scientific project more {{< glossary \"reproducible\" >}}. \n\nYou will learn more about version control, Git, and GitHub, in the [Introduction to Git and GitHub Section](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github) below. Much of the information in that section is described in the following papers. They both provide a helpful introduction to version control with Git and GitHub. \n\n:::{.reference_box}\n::::{.reference_box_header}\nVersion control resources:\n::::\n::::{.inner_block}\n- Blischak, J. D., Davenport, E. R., & Wilson, G (2016). [A Quick Introduction to Version Control with Git and GitHub](https://doi.org/10.1371/journal.pcbi.1004668), PLoS Computational Biology, 12(1).  \n  - this paper provides an overview of Git and GitHub for scientists who primarily work with the command line\n- Bryan, J (2018). [Excuse Me, Do You Have a Moment to Talk About Version Control?](https://doi.org/10.7287/peerj.preprints.3159v2) The American Statistician, 72(1), 20-27. \n  - this paper provides an overview of Git and GitHub for scientists and data scientists who primarily work with R and RStudio\n::::\n:::\n  \n***\n\n\n<!--\nDescribe the main biological questions for this case study.\nWhat will our analysis aim to answer? There can be more than 2.\nFill them in within the inner_block section, but leave the custom box syntax\nSee this previous case study as an example: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Main_Questions\n-->\n\n# **Main Question**\n***\n\n:::{.main_question}\n::::{.main_question_header}\nOur main question(s)\n::::\n::::{.inner_block}\n1. How does the use of version control contribute to transparent and reproducible science?\n1. How can Git and GitHub be used to facilitate collaboration on a research project?\n1. In this meta-analysis of infant gut microbiome samples, how do the original studies compare in their sampling designs? \n::::\n:::\n***\n\n\n# **Learning Objectives**\n***\n\n<!--\nReplace the shell content and enumerate the learning objectives in the referenced qmd files.\nFor an example of this section, see this previous Open Case Study: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Learning_Objectives\n\nStatistical LOs were provided in the original open case studies but they may be omitted here depending on the case study.\nBiological LOS were not provided in the original open case studies and should be included in all Bio-OCS case studies.\n-->\n\nIn this case study, we will introduce version control and describe why and how to use it to track a scientific project. We will use Git and GitHub to track a comparison of the sampling designs of studies used in a meta-analysis. \n\nThe skills, methods, and concepts that students will be familiar with by the end of this case study are:\n\n<u>**Data Science Learning Objectives:**</u>\n\n<!--\nEnumerate the Data Science or Bioinformatic specific learning objectives here.\n(Can have more than 3).\nFor an example, see this previous Open Case Study: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Learning_Objectives\n-->\n\n1. Understand ways in which version control facilitates reproducible science.\n1. Understand how version control works by recording differences between versions of a project.\n1. Follow a workflow to create and make changes to a repository with Git and GitHub.\n1. Make pull requests to propose changes to a codebase and request review from a collaborator.\n1. Organize a repository for a project with a README file and folders for data, figures, and results.\n\n\n\n::: {.content-hidden unless-meta=\"include-sections.stat-los\"}\n\n<u>**Statistical Learning Objectives:**</u>\n\n<!--\nEnumerate the Statistical specific learning objectives here. (\nCan have more or less than 3 or be omitted completely dependent on the open case study overal topic).\nFor an example, see this previous Open Case Study: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Learning_Objectives\n-->\n\n1. {Fill In}\n1. {Fill In}\n1. {Fill In}\n\n\n\n:::\n\n<u>**Biological/Bioinformatics Objectives:**</u>\n\n<!--\nEnumerate the topical Biological specific learning objectives here.\n(Can have less or more than 3).\nPrevious Open Case Studies do not have an example of this.\n-->\n\n1. Understand the value and limitations of combining data from multiple studies in a meta-analysis.\n1. Use visualizations to compare sampling designs across a set of studies. \n\n\n\n\n\n::: {.content-hidden unless-meta=\"include-sections.lo-map\"}\n\n<!--\nDon't adjust the shortcode or the table header in this file, only the markdown table contents\n-->\n\n## **Objectives Map**\n\n***\n\nThe following collapsed table shows what parts of the case study provide practice for different learning goals for those who are interested in a specific learning goal. \n\n::: {.callout-note collapse=\"true\" title=\"Objectives Map: Where It Is Covered\"}\n\n\n| Learning Goal          | Explanation / Practice                            | Location                |\n| :----------------------------------- | :-------------------------------------------------------------|:-----------------------|\n| Understand how version control facilitates reproducible science |Learn what reproducibility means and how version control contributes to reproducible analyses.| [Introduction to Git and GitHub](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github) |\n| Understand how version control works  | Learn about how version control works in terms of differences between commits. | [Introduction to Git and GitHub](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github) |\n| Create and make changes to a repository with Git and GitHub   | Create new repositories (both locally with Git and remotely with GitHub) and track changes over the course of an analysis. |[Introduction to Git and GitHub](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github), [Data Visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization) |\n| Make a pull request | Open a pull request to propose changes to a codebase, practice requesting a review from a collaborator. | [Pull Requests](https://www.opencasestudies.org/ocs-bio-version-control/#pull-requests) |\n| Organize a repository | Learn about why the files in this project are organized in this way, understand best practices in scientific project organization. | [Scientific Project Organization](https://www.opencasestudies.org/ocs-bio-version-control/#scientific-project-organization) | \n| Learn about meta-analyses | Learn about what meta-analyses are, why they are used, and limitations to combining data from multiple studies. | [Context](https://www.opencasestudies.org/ocs-bio-version-control/#context) | \n| Use visualizations to compare sampling designs | Make plots to compare the sampling designs of the original studies used in the meta-analysis described in this case study. |[Data Visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)|\n\n\n:::\n\n***\n\n\n:::\n\n\n<!--\nMore details on the background on the case study topic as well its relation to biomedical science.\nVideos or images may be helpful so this includes an example of embedding a video.\n-->\n\n# **Context**\n***\n\n### What is a microbiome?\n\nA microbiome is a collection of microorganisms that live in a particular environment. One commonly studied microbiome is the human gut microbiome. The bacteria that live in our gut help regulate our metabolism, protect us against pathogens, and perform other important roles in our health [@han2026host]. Studies have shown associations between changes to the gut microbiome and many diseases, including diabetes, autoimmune diseases, and Alzheimer's disease. \n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n![Bacteria from [Unsplash](https://unsplash.com/photos/red-strawberry-on-white-textile-2-Hv-Rg4asA)](img/bacterium.png)\n:::\n\n::: {.column width=\"50%\"}\n![Human digestive system from [Pixabay](https://pixabay.com/illustrations/abdomen-biology-bladder-body-8762848/)](img/digestive_system.png)\n:::\n\n:::\n\nMany features of the gut microbiome are established early in life, making the infant gut microbiome an important area of study [@wang2021metagenomic]. Researchers are particularly interested in understanding how the infant gut microbiome develops over time and how it relates to the maternal microbiome. To address these questions, several studies have collected {{< glossary \"longitudinal\">}} samples from infant-mother pairs. Sequencing microbiome samples is expensive, and individual studies are often limited in size. @wang2021metagenomic conducted a meta-analysis of eight of these studies, using this large data set to compare gut microbiome composition (which microbes are there?) and functional potential (what are the microbes capable of doing?) between infants and mothers.\n\n### What is a meta-analysis?\n\nA meta-analysis combines data or results from multiple studies investigating a common research question [@dersimonian1986meta]. By pooling information across studies, researchers can increase sample size, make better use of existing data, and generate a consensus result from a set of studies. However, meta-analyses must be conducted with care, as combining data from studies with different participant populations and different study designs can lead to misleading results. \n\nOne approach to meta-analysis combines summary results from each study. Another approach combines the original data from all studies and re-analyzes them jointly, accounting for systematic differences between studies [@andrade2025primer]. The latter approach requires access to the raw data from each study, but allows researchers to ask new questions and analyze the data from all studies using a common protocol. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e878f6c4a7_0_0.png){fig-alt='Types of meta-analyses' width=100%}\n:::\n:::\n\n\n@wang2021metagenomic used the second meta-analysis approach. They pulled the raw data from eight {{< glossary \"longitudinal\">}} studies of infant and mother gut microbiomes, processed all samples with a unified protocol, and conducted analyses on the pooled dataset while accounting for differences between studies. However, the success of this approach depends on how comparable the original studies are. This motivates our exploration of the similarities and differences between the various study cohorts. We want to understand how comparable these studies are, both in terms of sample size (how many samples are in each study?), and in terms of their longitudinal sampling study design (when in the lifespan of the infants did they take samples?).\n\n***\n\n<!--\nIntroduction to Git and GitHub (similar to \"Dashboard Basics\" section in school shootings OCS)\n-->\n\n# **Introduction to Git and GitHub**\n***\n\nBefore we start to address your project with Collab O. Rator, we will provide an introduction to version control with Git and GitHub. In this section, you will learn more about what Git and GitHub are, create a GitHub account, download Git software, and create your first version controlled project. Towards the end of this section we will return to the infant microbiome meta-analysis project. \n\n## Reproducibility and version control \n***\n\n:::{.definition_box}\n::::{.definition_box_header}\nReproducibility\n::::\n::::{.inner_block}\nThe ability for someone else the run the same analysis on the same data and get the same results as the original researcher.\n::::\n:::\n\nWhen conducting a scientific project, reproducibility is very important. If another researcher can use your data and code and generate the same results, then your conclusions are more credible to the scientific community. Version control is a tool that enables reproducible research by recording changes to a project over time. It has the following benefits:\n\n- When used carefully, it gives a complete history of changes made over the course of a project. This can be helpful for a research team to better understand what they did in one of their own previous studies!\n- It also provides a digital backup and an online repository of code and possibly also data (if it doesn't contain sensitive data). This can be very valuable if something happens to your computer.\n- Version control makes collaboration easier, automating the sharing of work in-progress and providing a system to propose and accept changes. \n\nWhile several tools exist for version control, we will introduce [Git](https://git-scm.com) and [GitHub](https://github.com), two of the most commonly used version control tools. Common alternatives to GitHub include [GitLab](https://about.gitlab.com/resources/) and [Bitbucket](https://bitbucket.org/product/guides).\n\n<details>\n<summary>More information on how reproducibility fits into the scientific process.</summary>\n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nReproducibility considerations\n::::\n::::{.inner_block}\n\nReproducibility is one concept that helps ensure that scientific projects and their results are valid and can be trusted by the scientific community. It can be considered as the intermediate goal between repeatability and replicability. \n\nAn experiment or analysis is repeatable if the **same** researcher can run it a second time, with the **same** data and code, and get the same results. \n\nFor that experiment or analysis to be reproducible, a **new** researcher needs to be able to run it with the **same** data and code and get the same result. \n\nFinally, conclusions from an experiment or analysis are replicable if a **new** researcher can run the same experiment or analysis with **new** data and draw the same conclusions. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f2d5a3e170_0_0.png){fig-alt='stairway of repeatability, reproducibility, replicability' width=100%}\n:::\n:::\n\n\n::::\n:::\n\n</details>\n\n## Why use version control? \n***\n\nConsider a typical workflow when you have a project with multiple files (for example: data, code, resulting figures). You likely have a folder on your computer where you keep these files. When you edit a file you save it, and you have access to the most recent version. You might run into a situation where you want to try something new, so you save \"project_file_old.R\" along with \"project_file_updated.R\" or perhaps \"project_file_july_2026.R\" or eventually \"project_file_final_version_4_final.R\". If you haven't saved an older version of a file but you wish you could revert to the version from last week before you tried something new, you would be out of luck. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3eb20c49c0b_0_0.png){fig-alt='why do you need version control (single person)' width=100%}\n:::\n:::\n\n\nSimilarly, think about how you might work on that same project with a collaborator. Perhaps you both have a folder on your computer for that project, and when you make an update you email the file to your collaborator, and they copy that update into their file, or save your file in their folder. Perhaps the two of you update the same file at the same time and then you have to go through line by line to merge the updates into a single version of the file. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f139628ce6_0_2.png){fig-alt='why do you need version control (single person)' width=100%}\n:::\n:::\n\n\nWhile both of these organizational systems can work well when carefully maintained, they are time consuming and prone to error. Version control is a tool that makes it easier to manage sets of files for projects. It automates several of the processes described above, and makes others dramatically easier. While version control was originally made for software engineers to work together on large projects, it is now commonly used for scientific projects as well.\n\nAt its core, version control lets the user track sequential changes to a set of files, with a short message attached to each version. Multiple people can work with the same version controlled folder, and different versions of files can automatically be merged, unless they are directly in conflict. \n\nOur discussion of version control is inspired by the following two papers. They both provide a helpful introduction to version control with Git and GitHub. \n\n:::{.reference_box}\n::::{.reference_box_header}\nVersion control resources:\n::::\n::::{.inner_block}\n- Blischak, J. D., Davenport, E. R., & Wilson, G (2016). [A Quick Introduction to Version Control with Git and GitHub](https://doi.org/10.1371/journal.pcbi.1004668), PLoS Computational Biology, 12(1).  \n  - this paper provides an overview of Git and GitHub for scientists who primarily work with the command line\n- Bryan, J (2018). [Excuse Me, Do You Have a Moment to Talk About Version Control?](https://doi.org/10.7287/peerj.preprints.3159v2) The American Statistician, 72(1), 20-27. \n  - this paper provides an overview of Git and GitHub for scientists and data scientists who primarily work with R and RStudio\n::::\n:::\n\n## What are Git and GitHub? \n***\n\nGit is a version control tool, and GitHub is a website for hosting files that are tracked with Git. Git works locally on your computer to record different versions of a project, and GitHub works online to provide a digital backup of files, let you connect with collaborators, and optionally create a web presence for your project. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_0.png){fig-alt='Git vs GitHub' width=100%}\n:::\n:::\n\n\n### Git\n\nThe files that are tracked as part of a version controlled project are contained in a repository. \n\n:::{.definition_box}\n::::{.definition_box_header}\nRepository (or repo for short)\n::::\n::::{.inner_block}\nA folder in Git that contains all of the files to be tracked for a project.\n::::\n:::\n\nWhen you set up a repository, Git will save an initial version of the files in that repository. Git works by tracking the evolution of files in a repository through a series of commits. \n\n:::{.definition_box}\n::::{.definition_box_header}\nCommit\n::::\n::::{.inner_block}\nA snapshot of the files in a repository at a certain time.\n::::\n:::\n\nAnother way to think about a commit is as a save point in a video game. This means that it saves your work up to a certain point in time. In the image below, a repository called **analysis_project** is tracked using version control, and it is made up of four commits. Each commit has a message that explains what work the commit represents. Within a commit, files can be added, edited, left unchanged, or deleted. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3fade600e50_0_0.png){fig-alt='Commits made to a repository called analysis_project. The first commit has the message \\'Create repo and add data\\' and data.csv is added. The second commit has the message \\'Add code to clean data\\' and data.csv has no change and code.R is added. The third commit has the message \\'Add code for initial plots\\' and data.csv has no change and code.R is edited. The fourth commit has the message \\'Fix plot themes\\' and data.csv has no change and code.R is edited.' width=100%}\n:::\n:::\n\n\nEach time that you tell Git to commit a version of your project, it will save it as a series of changes that list the differences between each file in the most recent commit and the current commit. We can look closer at an individual file and see how it changes across commits. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g409bc527eed_0_33.png){fig-alt='Changes to code.R file across commits. In Commit 2 the file is added, and code is added (denoted with plus marks) to load the data and remove missing ids. In Commit 3 the original code is still there, and code to plot is added afterwards (again denoted with plus marks). In Commit 4, one old line of code making the plot is removed and two new lines are added.' width=100%}\n:::\n:::\n\n\nHere you can see that green colored sections are additions and red colored sections are deletions. Git will not automatically make commits for you. You need to decide when to commit. If you want to return to a previous version of a project, you can only return to the version of files at any commit.\n\n### GitHub\n\nWhile you could only use Git locally to track versions of files, it is much more powerful when combined with GitHub. You can use GitHub to host a Git-tracked repository online. We will use the terms local repository and remote repository to distinguish between these. \n\n:::{.definition_box}\n::::{.definition_box_header}\nLocal\n::::\n::::{.inner_block}\nThe Git-tracked repository on your computer. \n::::\n:::\n\n:::{.definition_box}\n::::{.definition_box_header}\nRemote\n::::\n::::{.inner_block}\nThe online version of the repository tracked on GitHub. \n::::\n:::\n\nThere are several benefits to pairing your local repositories with remote repositories on GitHub. \n\n- You have a backup of files in case something happens to your computer.\n- You can easily work with collaborators.\n- You have a central location where your data (if appropriate) and code are stored for a project that can be viewed by and shared with other scientists.\n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nReproducibility considerations\n::::\n::::{.inner_block}\nA scientific paper is more reproducible if the data (or instructions to access the data) and code are publicly available, because other researchers can directly inspect and reproduce the analysis. While some papers have data and code \"available upon request\", hosting code (and data if appropriate) on GitHub makes it easier to share these files without requiring additional time and effort from the authors to respond to emails. This aligns with the open science movement, which aims to make research, data, and scientific software more transparent and accessible. \n::::\n:::\n\n### Creating new repositories\n\nThere are two ways to start new version controlled projects with Git and GitHub. You could create a new repository locally on your computer, track it with Git, and then \"push\" it to GitHub, creating a remote version of the repo. Or, you could create a new remote repository on GitHub and then \"clone\" it to your computer, creating a local version. We will provide examples of both workflows in the next section. \n\n:::{.definition_box}\n::::{.definition_box_header}\nPush\n::::\n::::{.inner_block}\nSending commits from the local version of a repository to the remote version of the repository on GitHub.\n::::\n:::\n\n:::{.definition_box}\n::::{.definition_box_header}\nClone\n::::\n::::{.inner_block}\nCreating a local repository that is a copy of a remote repository on GitHub. \n::::\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3d9461be06f_0_210.png){fig-alt='Git vs GitHub' width=100%}\n:::\n:::\n\n\nTypically, it is easier to create a new repository remotely with GitHub when started a version-controlled project from scratch. However, when you have already started work on a project and decide to version-control existing resources, you will want to create your new repository locally. \n\nIn this case study we will practice both approaches. First, in the [following section](https://www.opencasestudies.org/ocs-bio-version-control/#getting-started-with-git-and-github), you will practice creating a new repository from GitHub and cloning it to your local computer. Later, in the [section in which you create a repository for the case study analysis](https://www.opencasestudies.org/ocs-bio-version-control/#create-a-version-controlled-repository-for-your-project), you will practice working with an existing set of files and version-controlling them locally with Git. \n\n## Getting started with Git and GitHub\n***\n\n### Creating a GitHub account\n\nWe will start with GitHub. If you do not have an account, make one [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/signup&ved=2ahUKEwjRoqKR48-TAxVIyOYEHYMpA6QQFnoECA0QAQ&usg=AOvVaw0a6qEmIZVdziwPUb-hFApr). \n\nWhen you choose a username, consider [advice](https://happygitwithr.com/github-acct) from Jenny Bryan (a data scientist who has thought a lot about version control). She suggests choosing a username that incorporates your real name and that you would be comfortable sharing with professional colleagues. \n\n### Creating a new GitHub repository\n\nNow that you have a GitHub account, you can create your first repository. The goal of this repository is to get you set up and to practice with Git and GitHub. You will later make another repository to use for the case study analysis.\n\nTo create your repository:\n\n- [ ] click on the menu bottom (three horizontal lines)\n- [ ] click \"Repositories\"\n- [ ] click the green button that says \"New repository\" \n\nThis will take you to a new page. GitHub will automatically set you as the owner of the repository, and you can choose a name. Let's call this repository \"my-first-repository\". \n\nA few notes on naming repositories:\n\n- keep the name descriptive but short\n- don't use spaces, instead use \"-\", \"_\", or \".\" \n\nNext, add a short description for this repository. Toggle the bottom next to \"Add README\" to \"On\". For now, we won't worry about visibility, a template, .gitignore, or license. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e1f8f72664_0_798.png){fig-alt='Creating first repository' width=100%}\n:::\n:::\n\nUse the drop-down sections to learn about each of the configuration options. \n\n***\n\n<details> <summary> Visibility </summary>\n\nBy default your repository will be set to public, which means that anyone can view all of the files contained in it. If you would prefer that only you and collaborators that you add can view the contents, you can set the visibility to private. Please note that this is not ***truly*** private, so please do not host protected heath information or other forms of data that require extra protection on GitHub even with a private repo.\n\n</details>\n\n<details> <summary> Template </summary>\n\nA template is an existing repository that you can use as a template for new repositories. A repository made from this template will have the same folders and files as the template repository. You can make any repository that you have access to into a template. Typically, you will not use a template when creating a new repository. \n\n</details>\n\n<details> <summary> README </summary>\n\nWe will discuss README files in more detail in the project organization [section](https://www.opencasestudies.org/ocs-bio-version-control/#scientific-project-organization), but a README file explains what your repository is used for and what files it contains. If you are creating a repository from scratch, we strongly suggest that you include a README. \n\n</details>\n\n<details> <summary> .gitignore </summary>\n\nYou may have files in your repository that you don't want to commit, such as large data files or intermediate files (we will discuss which files you may not want to commit later in the project organization [section](https://www.opencasestudies.org/ocs-bio-version-control/#scientific-project-organization)). If there is a file that you don't want to track with version control, you can add it to the .gitignore file, to tell Git to ignore it. When you click the down arrow next to \"No .gitignore\" it will provide several templates. For a project using R, the \"R\" template is a good place to start. It includes files often associated with projects in R that are not typically tracked with version control.\n\n</details>\n\n<details> <summary> License </summary>\n\nA license is a legal document that states who can use your code. Although it may seem counterintuitive, a license typically makes your code more \"open\", which means that other people can use it with fewer restrictions. There are two main types of licenses used for most R projects hosted on GitHub: permissive (MIT) and copyleft (GPL). A permissive license means that people can use your code with minimal restrictions. A copyleft license means that any code that incorporates your code must also be open-source. You can read more about licenses for open-source projects [here](https://opensource.guide/legal/), or use [this resource](https://choosealicense.com) to see what license might be most appropriate for your project. \n\n</details>\n\n***\n\nFor more information on any of these components of a new repository, see GitHub's [documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-new-repository) for creating new repositories.\n\nOnce you click \"Create repository\", you will be brought to the GitHub page for your repository. GitHub URLs all have the same format: \"https://github.com/your_user_name/your_repository_name\".\n\nIf you look at your repository, you will see that it has one file: README.md. This is where you will document what is contained in your repository, and it will serve as a homepage for your project. It is written in Markdown, a language that can be used to format documents (you can find more information about how Markdown works and its syntax [here](https://www.markdownguide.org)). You will now edit the README:\n\n- [ ] click the pencil on the upper right of the README\n- [ ] add a new line to your README document that says \"Adding a new commit to my README.\" \n- [ ] click the green button that says \"Commit changes\"\n- [ ] provide an informative commit message, something like \"Add new line to README.md\" \n- [ ] click the green button that says \"Commit changes\"\n- [ ] click the repository name in the upper left to navigate back to the home page\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_13.png){fig-alt='Image of first repository' width=100%}\n:::\n:::\n\n\nLet's now look at the commit history for this repository. We can do that by clicking where it says \"2 Commits\" just below the green \"Code\" button. \n\nThis brings us to a list of commits for this repository. You should see two commits, the initial commit that created the repository and the one you just made when you edited the README file. Click on the title of the newer commit. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_68.png){fig-alt='List of commits' width=100%}\n:::\n:::\n\n\n\nThis will bring you to information about the commit. Each commit has an alphanumeric hash (set of letters and numbers), which uniquely identifies that commit. In this view, you can see each file that has been changed in your commit, as well as the changes to the files. Here, we can see with the plus signs that you've added a line to the README. This type of visual representation of a commit, in terms of the changes between files, can be helpful when you want to understand the history of a project. \n\n<details>\n<summary>GitHub issues: a convenient to-do list for your repository</summary>\nOne thing that you'll see when looking at your new repository is a tab in the upper left corner (just above the repository name) that says \"Issues\". Click on this \"Issues\" button.\n\nAn issue is a way to keep track of ideas, tasks to complete, errors to resolve, or anything else related to a GitHub repo (see how GitHub describes issues [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues)). Issues are also a good place to collaborate. You can tag people with their GitHub usernames in an issue, which will trigger an email notification. Multiple people can comment on an issue, so you can have a discussion about how to resolve the issue. The benefit of this over an email thread is that other collaborators can view this conversation, as well as other GitHub users who may want to know about the issue and resolution as well. Once an issue is considered resolved (for example, the task it mentions has been completed or the error it mentions has been fixed), then the issue can be closed. However, the GitHub repo will retain a searchable list of closed issues. When used frequently, this can be a helpful record of the development of a project. \n</details>\n\n### Installing GitHub Desktop \n\nNext, we will move from interacting with GitHub to interacting with Git. First, we recommend that you install GitHub Desktop. This is a GUI (graphical user interface) that makes it easier for us to interact with Git locally. While we will use GitHub Desktop in this case study, another common way to interact with Git is through the {{< glossary \"command line\">}} on your computer. If you are already comfortable using the command line, you may prefer this to GitHub Desktop. When we use GitHub Desktop for version control tasks in this case study, we will also provide the command line code for all Git operations.\n\n<details> <summary> More information about the command line. </summary>\n\nYou may have also heard this called the *shell*, *terminal*, *console*, or *command prompt*. The command line lets us interact with our computers by typing commands (as opposed to using a graphical user interface (GUI) which involves clicking buttons and menus). These commands let you perform tasks such as navigating and modifying your file system, installing programs, running code, and working with Git. Each of these tasks can also be performed using a graphical interface. Some people prefer the visual layout of a GUI, while others prefer the simplicity and centralized control of the command line. \n\n</details>\n\nFollow this [link](https://desktop.github.com/download/) to install GitHub Desktop. \n\n<details> <summary> If you are using a Mac, it will ask you if your Mac has an Apple silicon or Intel chip. Click here for more information. </summary>\n\nTo check whether your Mac has an Apple silicon chip or an Intel chip, click the Apple menu \n-> \"About This Mac\". If the information window shows \"Chip\" then your Mac uses Apple silicon. If the information window shows \"Processor\" then your Mac uses an Intel processor. \n\n</details>\n\n### Installing Git\n\nIf you have successfully installed GitHub Desktop, then Git is already installed on your system and no further installation is required. \n\n<details> <summary> If you are unable to install GitHub Desktop or would prefer not to install GitHub Desktop, you can install Git using the command line. Click here for more information. </summary>\n\nFirst, we will see if Git is installed on your computer, and install it if not. We will start by opening the command line. \n\n::: {.panel-tabset}\n#### Mac\n\nOpen the application called \"Terminal\". You can find this by using Spotlight Search and searching for \"Terminal\". \n\n#### Windows\n\nOpen the application called \"Command Prompt\". You can find this by using the Start menu and searching for \"Command Prompt\". You could instead use the PowerShell by searching for \"PowerShell\" instead. \n\n#### Linux \n\nOpen the application called \"Terminal\". You can find it by using your system’s application menu and searching for \"Terminal\".\n\n:::\n\nIn the command line, type:\n\n::: {.shell}\n```bash\ngit version\n```\n:::\n\nIf the output tells you which version of Git is installed, then you already have Git. For example, if Git is already installed, the output may look like:\n\n::: {.shell}\n```bash\ngit version 2.50.1\n```\n:::\n\nIf you see a message like \"git: command not found\" or \"git is not recognized\" or a prompt to install something, then Git is not installed and you'll need to install it. \n\nTo install Git, follow these instructions:\n\n::: {.panel-tabset}\n#### Mac\n\nFollow [these instructions](https://github.com/git-guides/install-git#install-git-on-mac).\n\n#### Windows\n\nFollow [these instructions](https://github.com/git-guides/install-git#install-git-on-windows).\n\n#### Linux \n\nFollow [these instructions](https://github.com/git-guides/install-git#install-git-on-linux).\n\n:::\n\n</details>\n\n### Connecting Git to GitHub\n\nIf you have GitHub Desktop installed, we can use it to authenticate your GitHub account with Git. We could also do this with the command line, but GitHub Desktop makes it easier. \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nWhen you open GitHub Desktop, it will prompt you to sign into GitHub. If it does not, then follow [these instructions](https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github-in-github-desktop), choosing instructions for Mac or Windows based on your operating system.\n\nNext, we will configure Git. This means that you will tell Git your name and email. Follow [these instructions](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-git-for-github-desktop), again choosing instructions for Mac or Windows based on your operating system. \n\n#### Command line \n\nFirst we will tell Git your name and email address. Open the command line and enter the following:\n\n:::: {.shell}\n```bash\ngit config --global user.name \"Your name here\"\ngit config --global user.email \"Your email here\"\ngit config --global --list\n```\n::::\n\nThe third line should print your name and email correctly.\n\nNext, you need to connect your GitHub account to your local Git. \n\nGitHub no longer supports using passwords to connect Git and GitHub, so you'll instead need to use a Personal Access Token (PAT). To create a token, [click this link to go to your settings for tokens](https://github.com/settings/tokens). In order to connect your token to your computer do the following:\n\n- [ ] click \"Generate new token\"\n- [ ] choose \"Generate new token (classic)\"\n- [ ] give your token a name and expiration date\n- [ ] select the \"repo\" scope\n- [ ] click \"Generate Token\"\n- [ ] copy the token to your clipboard, or keep this window open (you will not be able to access this again)\n\nNow, open the command line and run the following:\n\n:::: {.panel-tabset}\n\n#### Mac\n\n::::: {.shell}\n```bash\ngit config --global credential.helper osxkeychain\n```\n:::::\n\n#### Windows\n\n::::: {.shell}\n```bash\ngit config --global credential.helper manager\n```\n:::::\n\n#### Linux \n\nIf available, run:\n\n::::: {.shell}\n```bash\ngit config --global credential.helper manager\n```\n:::::\n\nIf that does not work, use: \n\n::::: {.shell}\n```bash\ngit config --global credential.helper cache\n```\n:::::\n\n::::\n\nThis tells Git to remember the login credentials that we will provide so you won't need to enter them each time. \n\nNext, we need to trigger a GitHub credentials check. We will do this by cloning the repository that you made (this means we will make a local version of this repo). See this [section if you still need to make the repository](https://www.opencasestudies.org/ocs-bio-version-control/#creating-a-new-github-repository). Run the following, replacing \"your_username\" with your username:\n\n:::: {.shell}\n```bash\ngit clone https://github.com/your_username/my-first-repository.git  \n```\n::::\n\nRunning this command should prompt you to give a username and password. Use your GitHub username, and the PAT you just generated as the password (do not use your GitHub password). Git will now store these credentials so you won't need to enter them again. When your PAT expires, you will need to follow these steps again. \n\n:::\n\n### Creating a local clone of your GitHub repository \n\nYou've finished setting up GitHub, Git, and GitHub Desktop, great job! Now, we can create a local version of \"my-first-repository\" that you made on GitHub earlier. \n\nMaking a local copy of a repository that is hosted on GitHub is called \"cloning\". Start by navigating to your repository on GitHub, and copy the URL. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_38.png){fig-alt='Cloning repo' width=100%}\n:::\n:::\n\n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nFrom GitHub Desktop, go to \"File -> Clone Repository\" and then provide the URL to your GitHub repository. Now, you should be able to see a window in GitHub Desktop that corresponds with \"my-first-repository\". If you click on history, you can see a list of commits to this repository. \n\n\n#### Command line \n\nYou were already asked to clone this repository in the last section, in order to trigger Git's login credentials. If you haven't done that, open the command line and enter the following, replacing \"your_username\" with your username:\n\n:::: {.shell}\n```bash\ngit clone https://github.com/your_username/my-first-repository.git  \n```\n::::\n\nYou will know that this has worked if you see the following output:\n\n:::: {.shell}\n```\nCloning into 'my-first-repository'...\n```\n::::\n\n:::\n\nNext, you will open the local repository. RStudio and Positron have different approaches to opening folders. \n\n::: {.panel-tabset}\n#### RStudio\n\nThe easiest way to work with a Git-tracked repository in RStudio is to make an RStudio project. A project is a folder that R can open as a self-contained unit. The most useful part of an RStudio project is that you can use relative file paths; the folder that you used to create the project will be the root of any relative file path. Using relative file paths for a project, as opposed to absolute file paths that are specific to your personal computer, make it easier to collaborate with other people.\n\nIn order to open your Git-tracked repository as an RStudio project, open RStudio and click \"File -> Open Project\". This should prompt you to open your file browser, and you should navigate to the folder called \"my_first_repository\", which was created when you cloned the repository. Once you select the correct folder, RStudio will open the project. If you look at the \"Files\" panel, you'll see the README that you made for \"my_first_repository\" on GitHub. You will additionally see a file called \"my_first_repository.Rproj\". This file is automatically made by RStudio when opening a new project, and saves information about the project. \n\n#### Positron\n\nIn Positron, click \"File -> Open Folder...\" and then navigate to the folder called \"my_first_repository\", which was created when you cloned the repository. Once you select the correct folder, Positron will open it. In the file explorer, you will be able to see the README that you made for \"my_first_repository\" on GitHub. \n\n#### Other R IDE\n\nIf you are using another R IDE besides RStudio or Positron, you should look up instructions for opening a folder in your environment. \n\n:::\n\n#### Stage, commit, push\n\nNext, we will create a new file locally. Create a new R file within \"my-first-repository\" and call it \"01-calculations.R\". In this file, include the following:\n\n::: {.rcode}\n```r\nx <- 103\ny <- 5\nx * y\n```\n:::\n\nSave this file. Now, we will discuss how to track a new file with Git. \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNow, navigate back to GitHub Desktop. Where it previously said \"no local changes\", it now will show changes to your repository. You should see your new file name \"01-calculations.R\" with a green plus next to it. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_84.png){fig-alt='GitHub Desktop with a new file added' width=100%}\n:::\n:::\n\n\n<details>\n<summary> If you are using RStudio, you will likely see additional added files here. </summary>\nWhen you created a RStudio project, RStudio automatically created a \"my-first-repository.Rproj\" file to manage the project, and a \".gitignore\" file to avoid tracking several hidden files that manage the project. Because these files were added, they are now included in the changed files that you see in GitHub Desktop. It is typically recommended to track your .Rproj and .gitignore files with Git. \n</details>\n\nBy default, the box next to added or updated files is checked. This means that each of these files are \"staged\", or ready to be included in a commit and added to the repository history. If you uncheck the box, you are telling Git that for now you would not like to track that file with version control. If you would like to tell Git to never track files, you should add them to a .gitignore file. \n\nIn the lower left corner you will see a box that says \"Summary (required)\" and \"Description\". This is where you will put your commit message. \n\nFor this commit, you might use the summary \"Add new file '01-calculations.R' to do calculations.\"  \n\nOnce you've added the commit message, you are ready to commit these files. Click \"commit to main\". Now these changes have been entered into the version control history of your repository in Git. \n\nWe have one more step to update the GitHub repository, which is to \"push\" these files to GitHub. This is the step that transfers local changes to the remote repository. Once you commit you will see a box in GitHub Desktop that says \"Push commits to the origin remote\". Click this box. \n\nNow, open your project in GitHub. You should now see the file that you added locally, as well the commit message. \n\n#### Command line \n\nOpen the command line, navigate to the folder that contains your repository, and enter the following:\n\n:::: {.shell}\n```bash\ncd my-first-repository\n```\n::::\n\nThis will move you into the repository folder. Next, enter:\n\n:::: {.shell}\n```bash\ngit status\n```\n::::\n\nThis will list untracked files, which are files that Git is not keeping track of.\n\n<details>\n<summary> If you are using RStudio, you will likely see additional added files here. </summary>\nWhen you created a RStudio project, RStudio automatically created a \"my-first-repository.Rproj\" file to manage the project, and a \".gitignore\" file to avoid tracking several hidden files that manage the project. Because these files were added, they are now included in the changed files that you see in GitHub Desktop. It is typically recommended to track your .Rproj and .gitignore files with Git. \n</details>\n\nIn order to tell Git to start tracking files, we need to \"stage\" the files for version control. We do this with the `git add` command:\n\n:::: {.shell}\n```bash\ngit add 01-calculations.R\n```\n::::\n\n<details>\n<summary> If you are using RStudio, you can also track the additional files that have been created. </summary>\n:::: {.shell}\n```bash\ngit add my-first-repository.Rproj .gitignore\n```\n::::\n</details>\n\nNext, we will commit the staged files (remember, this is similar to creating a snapshot of these files, or to creating a save point in a video game). The command `git commit -m \"...\"` commits the staged files and the flag `-m` adds a commit messages. \n\nFor this commit, you might use the summary \"Add new file '01-calculations.R' to do calculations.\"  \n\n:::: {.shell}\n```bash\ngit commit -m \"Add new file '01-calculations.R' to do calculations.\"\n```\n::::\n\nWe have one more step to update the GitHub repository, which is to \"push\" these files to GitHub. This is the final step that updates the GitHub repository to include the changes that we made locally. To push, enter: \n\n:::: {.shell}\n```bash\ngit push \n```\n::::\n\nNow, open your project in GitHub. You should now see the new file that you made locally, as well the commit message. \n:::\n\nA few pieces of advice to consider for your commit messages:\n\n- A commit message should be informative. Think of a collaborator (or yourself in a few months) reading the commit message. It should tell the reader why you've made this commit. Did you add a file? Did you fix a bug in the code? Did you remove an outdated data file? Your commit history, when maintained thoughtfully, can provide a record of why you made changes throughout a project. \n- A commit message should be concise. Avoid adding too many unnecessary details here. The reader can always look at the differences in files for the commit to see exactly what you've done. \n- In a public repository, the commit message will be visible to anyone and exist as long as the repository does. Make sure that your message is appropriate and you'd be comfortable with colleagues seeing it. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f139628ce6_0_174.png){fig-alt='good and bad commit messages' width=100%}\n:::\n:::\n\n\n#### Pulling updates from GitHub\n\nYou've learned how to make updates locally, and stage, commit, and push these changes so that the GitHub repository includes those updates. While \"pushing\" sends updates from a local repository to the remote repository on GitHub, \"pulling\" sends updates from the remote GitHub repository to your local repository. To practice pulling, we're going to make another change and commit from GitHub, and then pull that commit into our local repository. We'll follow the same steps to make a change and commit on GitHub:\n\n- [ ] click the pencil on the upper right of the README\n- [ ] add a new line to your README document that says \"Adding another commit from GitHub.\" \n- [ ] click the green button that says \"Commit changes\"\n- [ ] provide an informative commit message, something like \"Add one more new line to README\" \n- [ ] click the green button that says \"Commit changes\"\n- [ ] click the repository name in the upper left to navigate back to the home page\n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNow, return to GitHub Desktop. Do the following: \n\n- [ ] In the upper banner, click where it says \"Fetch origin\". It should then update and say \"Pull origin\".\n- [ ] Click \"Pull origin\". \n- [ ] Go to the \"History\" pane, and you'll see the most recent commit that you made on GitHub, now included in your local repository. \n\nIf you return to RStudio or Positron and open \"README.md\", you will now see the update that you made on GitHub. \n\n#### Command line \n\nOpen the command line, navigate to the folder that contains your repository, and enter the following:\n\n:::: {.shell}\n```bash\ngit pull\n```\n::::\n\nIf you return to RStudio or Positron and open \"README.md\", you will now see the update that you made on GitHub. \n\n:::\n\n### What you've done\n\nIn this section you have made a GitHub account, installed Git and GitHub Desktop, configured Git and GitHub to be connected so they can receive updates from each other, and made your first repository. You've learned how to make changes to the remote on GitHub and transfer them to the local repository on your computer, as well as do the opposite. \n\nIn a typical GitHub workflow, you will rarely be making changes on GitHub (github.com). Instead, you will often be working with one or multiple collaborators on a repository. Once your collaborator makes changes locally, they can push those changes to GitHub, and then you can pull those changes to your local copy of the repository. This process will continue cyclically while you collaboratively work on a project. Note that this is a simplified system where you take turns to make changes, in practice you can work on the project at the same time (using branches which will be discussed later in the Branches [section](https://www.opencasestudies.org/ocs-bio-version-control/#branches)).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f139628ce6_0_206.png){fig-alt='Git and GitHub workflow' width=100%}\n:::\n:::\n\n\n## Create a version controlled repository for your project \n***\n\nNow, we will return to the project with Collab. O. Rator. In the previous section, you created a repository on GitHub, and then cloned it to make a local copy. Here, you will practice the other approach for creating a new version-controlled repository. You will start with a local folder, track it with Git, and then create a remote version of the repository on GitHub. \n\nFirst, download the .zip file [here](https://github.com/opencasestudies/version_controlled_infant_gut_analysis/blob/main/version_controlled_infant_gut_analysis.zip). Your browser may automatically unzip this file to create a folder called \"infant_gut_files\", if not then unzip the file manually (this typically involves right clicking or double clicking depending on your operating system). \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNow, go to GitHub Desktop and do the following: \n\n- [ ] click the button \"Add\" in the top right\n- [ ] click \"Create New Repository\"\n- [ ] give your repository the name \"infant_gut_analysis\".\n- [ ] leave the box \"Initialize this repository with a README\" unchecked (because a README is already included in the set of files). \n- [ ] under Git Ignore choose \"R\" and under License choose \"MIT License\". \n\nNow, copy the contents of the \"infant_gut_files\" into the new repository that you just created with GitHub Desktop\n\nOnce you add these files, return to GitHub Desktop. You should see a set of changed files, with check marks next to them to denote that they are staged. \n\n- [ ] add a commit message and commit this change\n- [ ] you should then see an option to \"Publish repository\", click this\n- [ ] you should now see the option \"Open the repository page on GitHub in your browser\". \n\nClicking this will bring you to the new GitHub repo that you just made for this project! \n\n#### Command line \n\nOpen the command line, navigate to the folder that you have unzipped, and enter the following:\n\n:::: {.shell}\n```bash\ngit init -b main\n```\n::::\n\nThis command tells Git to create a version controlled repository in the current folder. Don't worry about understanding the `-b main` part of the command for now, we will discuss it in a later section about branches. \n\nIf you look into your folder you will not see any changes. However, this command creates a hidden `.git` folder within the current folder, which contains the files that are needed to start tracking this folder with Git. It is now a Git-tracked repository. \n\nBecause we've created a Git repository from a folder of existing files, we should be sure to add a .gitignore file before staging and committing. While we could create an empty file called \".gitignore\" and add files to it that we don't want to track, we will instead download a .gitignore file from GitHub that includes files that are typically not tracked in workflows that use R. While most of the files in this .gitignore won't be included in your project, there is no harm in including files in a .gitignore file that don't exist in the repository. \n\nIn the command line, enter:\n\n:::: {.shell}\n```bash\ncurl -o .gitignore https://raw.githubusercontent.com/github/gitignore/main/R.gitignore\n```\n::::\n\nNow we will stage files, so that Git knows to track them, and commit them, so that Git saves the set of files as part of the history. \n\nFirst, check which files are currently untracked or modified.\n\n:::: {.shell}\n```bash\ngit status\n```\n::::\n\nWhen you run `git status`, look for files listed under *\"Untracked files\"* (new files not yet tracked) or *\"Changes not staged for commit\"* (modified files that have not yet been added). You can then choose which files to add. In this repo, because the data is small and publicly available, we will add and commit the data folders. If this is not the case for your data, you should list data files or folders in your .gitignore file, to avoid tracking them. \n\n:::: {.shell}\n```bash\ngit add README.md 01_pull_study_data.R 02_wrangle_data.R\nprocessed_data raw_data .gitignore\ngit commit -m \"track all files for infant gut project\" \n```\n::::\n\nIn the `git add` command above, we track all scripts (.R files) and data. We do not track the figures and results folders for now because Git will not track empty folders. Once we add figures and results to these folders, we can then version control them (if we want to include these outputs in our version controlled repository). \n\n<details>\n<summary> Note on staging all files in a repository </summary>\nYou may see examples in other Git tutorials using `git add .`, which stages all files in the current directory. While convenient, you should use this with caution, as it can unintentionally include files you do not want to track, such as large data files, sensitive data, or auxiliary files generated by your computer (e.g., .Rproj, .Rproj.user, .DS_Store). While this can be avoided by adding all of these files to your .gitignore file, it is generally safer to add individual files and folders to your `git add` command that you'd like to track. \n</details>\n\nNext, you will need to create an empty repository on GitHub. Go to GitHub and create a new repository called \"infant_gut_analysis\". Review [these steps](https://www.opencasestudies.org/ocs-bio-version-control/#creating-a-new-github-repository) if needed, but importantly, this time **do not check \"Initialize with README\"**, this should be a fully empty repository. Copy the URL of this repository. \n\nNow, return to the command line and enter (replacing the URL below with the URL that you just copied):\n\n:::: {.shell}\n```bash\ngit remote add origin https://github.com/your_username/infant_gut_analysis.git\n```\n::::\n\nFinally, we'll push the files that we have locally to the remote repository on GitHub. Use the following command:\n\n:::: {.shell}\n```bash\ngit push -u origin main\n```\n::::\n\nBecause this is the first time pushing to the remote repository, we need the `-u` flag to tell Git to remember where to send our changes. `origin` refers to the remote GitHub repository (that we set in the previous command), and `main` refers to the default version of the repository.\n\n:::\n\n### Open this repository in RStudio or Positron\n\nFinally, we will open this repository with RStudio or Positron. \n\n::: {.panel-tabset}\n#### RStudio\n\nIn order to open your Git-tracked repository as an RStudio project, open RStudio and click \"File -> Open Project\". This should prompt you to open your file browser, and you should navigate to the folder called \"infant_gut_analysis\". Once you select the correct folder, RStudio will open the project. \n\n#### Positron\n\nIn Positron, click \"File -> Open Folder...\" and then navigate to the folder called \"infant_gut_analysis\", which was created when you opened the .zip file. Once you select the correct folder, Positron will open it. \n\n#### Other R IDE\n\nIf you are using another R IDE besides RStudio or Positron, you should look up instructions for opening a folder in your environment. \n\n:::\n\n## Branches\n***\n\nOne useful feature of Git is the ability to make branches. A branch is a history of commits, and by default a repository that is tracked by Git starts with the \"main\" branch. Multiple branches provide parallel versions of the repository that can be developed separately. For example, you may have a version of your analysis and results in the main branch, but you want to experiment with changing a parameter. You could do this in a separate branch. This would let you work on the experimental version of your analysis while also having a stable version of your analysis elsewhere. You can switch between branches depending on what version of the analysis you want to work with on a given day. If you eventually decide that you want to move forward with the changed parameter, you can merge your experimental branch back into your main branch. \n\n:::{.definition_box}\n::::{.definition_box_header}\nMerge\n::::\n::::{.inner_block}\nIntegrating changes from one branch into another branch. \n::::\n:::\n\nHere is an example of a workflow, in which a Git user makes a \"plotting\" branch from the \"main\" branch, adds commits to both branches, and then eventually merges the \"plotting\" branch back into \"main\". Click through the tabs from left to right to follow the branching process. \n\n::: {.panel-tabset}\n#### Step 1\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_733.png){fig-alt='branch workflow: start with Main branch' width=100%}\n:::\n:::\n\n\n#### Step 2\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_774.png){fig-alt='branch workflow: add Plotting branch' width=100%}\n:::\n:::\n\n\n#### Step 3\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_796.png){fig-alt='branch workflow: Commit to Plotting branch' width=100%}\n:::\n:::\n\n\n#### Step 4\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_818.png){fig-alt='branch workflow: Separately, commit to main branch' width=100%}\n:::\n:::\n\n\n#### Step 5\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_840.png){fig-alt='branch workflow: merge Plotting back into Main' width=100%}\n:::\n:::\n\n\n:::\n\nIf there are no lines of code in any files that are directly in conflict, then merging will automatically combine the sets of files into a single version to move forward with. If there are lines that are directly in conflict, this will create what is called a merge conflict (merge conflicts are explained further in [this section](https://www.opencasestudies.org/ocs-bio-version-control/#troubleshooting-git-and-github)). \n\nHere is an example of a file from the branching workflow above that can be merged automatically. The lines with red minus signs are deleted within the particular commit, and the lines with green plus signs are added within the particular commit.  \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_130.png){fig-alt='file before and after merge' width=100%}\n:::\n:::\n\n\nBranches are also helpful when working with collaborators. If you are developing a new part of an analysis, you can do it in a separate branch. When you are ready for your collaborator to review your work, you can submit a \"pull request\", which is a request to merge your branch with the main branch. Your collaborator can review all of the changes between your main branch and the new branch, and either approve the pull request or request edits before merging. You can read more about pull requests in [this section](https://www.opencasestudies.org/ocs-bio-version-control/#pull-requests).\n\n### Create a new branch for this analysis \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nYou will create a new branch with GitHub Desktop. \n\nIn GitHub Desktop:\n\n- [ ] navigate to the tab in the top left of the window that says \"Current Branch\" \n- [ ] click on this tab, and you should see a button that says \"New Branch\"\n- [ ] name your new branch \"study_comparison\". \n\n#### Command line \n\nOpen the command line, navigate to the folder that you have unzipped, and enter the following:\n\n:::: {.shell}\n```bash\ngit checkout -b study_comparison\n```\n::::\n\nWhen you create a new branch, you can name it by providing a new branch name after using the `-b` flag (we name the new branch \"study_comparison\" above). When you want to move to an existing branch, you can use `git checkout` without the `-b` flag. For example, if you want to navigate back to the main branch, you could use the command `git checkout main`. \n\n<details><summary>A newer Git command to use with branches: `git switch`</summary>\n\nGit is a piece of actively maintained software, and will continuously be updated and improve. In 2019, the `git switch` command was introduced to work more clearly with branches. The command `git switch -c study_comparison` is equivalent to the command `git checkout -b study_comparison`, where the `-c` flag creates a new branch. Similarly, the command `git switch main` is equivalent to `git checkout main`, and will move you to whatever branch you have specified (in this case the main branch). When you look at Git documentation, you may see `git checkout` used in older material and `git switch` used in newer material when creating or moving between branches, but either command will work in these situations. You can read [this article about why `git switch` was created](https://www.datacamp.com/tutorial/git-switch-vs-checkout) if you would like to learn more.\n\n</details>\n\n:::\n\n## Tips for Git and GitHub\n***\n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nTips\n::::\n::::{.inner_block}\n- Commit often. A history will not be helpful if you run an entire analysis locally and then commit everything in a single commit. \n- If you are working on a repository with multiple contributors, make sure to pull each time you work in order to work on the most up-to-date version of the repository. If you don't, Git will let you know and help you to do so (check out this resource about more complicated [merging when you forgot to pull](https://medium.com/@Spritan/merge-vs-rebase-vs-fast-forward-mastering-git-integration-strategies-3ba8e652d93e)).  \n- Never use version control to track files with passwords or other sensitive information. If you have there are ways to remove these files and change the Git history, but this should be considered a last resort. Instead, add any files with sensitive information to your .gitignore.\n\n    - If passwords, access tokens, API keys, or other credentials are accidentally committed and pushed to a remote repository on GitHub (either public or private), they should be considered compromised and changed as soon as possible, and all collaborators who work with that repository should be alerted. \n\n::::\n:::\n\n***\n\n<!--\nProject organization (similar to \"Dashboard Basics\" section in school shootings OCS)\n-->\n\n# **Scientific Project Organization**\n***\n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nReproducibility considerations\n::::\n::::{.inner_block}\nAlthough this is not directly related to {{< glossary \"version control\">}}, there are some useful ideas to know about organizing a scientific project, that will improve {{< glossary \"reproducibility\">}}. While most people have their own approaches to scientific project organization, there are a few principles that most successful organization schemes have in common. More information can be found in [this reproducibility course](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/organizing-your-project.html).\n\n- file names are concise but informative\n- there is one central folder to contain all files for each project\n- there is a central file (often called the {{< glossary \"README\">}}) that explains what files are included and how to use them to run the analysis\n- there are folders to keep similar files together \n  - data folder (this could be split into raw data and processed data)\n  - figures folder for any figures made for the analysis\n  - results folder for any results that should be shared or would take moderate or more computation to re-generate\n- scripts are numbered in the order that they should be run to generate results\n\n::::\n:::\n\n## Organization of this project \n***\n\nIf we look at the files contained in the \"infant_gut_analysis\" repository, they follow the recommendations provided above. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3e3d77952e3_0_0.png){fig-align='center' fig-alt='File viewer for files in this repository' width=100%}\n:::\n:::\n\n\n## README\n***\n\nA README file should describe the files related to your scientific project. It should describe where inputs come from, what each script does, and where outputs are generated. If someone reads through your README, they should know where to find each component of your analysis. \n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nRead through the README.md file for this project. Which script generates \"sample_metadata.csv\"? \n<details><summary>Answer</summary>\nThe script \"01_pull_study_data.R\" generates \"sample_metadata.csv\". \n</details>\n::::\n:::\n\n## Project organization with Git and GitHub\n***\n\n### Empty folders\n\nOne thing that often surprises new Git users is that any empty folders may exist on your computer but will not be tracked by Git until they have content. So while we see \"figures\" and \"results\" in the set of files from the folder \"infant_gut_files\", they  cannot be tracked by Git or hosted on GitHub until they have content. If you want to track an empty folder before it has content, you can add a placeholder file into the folder, and remove it later once the folder has content.\n\n### Which files to track with Git \n\nRecall that version control lets you track project files as they change throughout the research process. Therefore, there are some files that should always be tracked with version control, some files that should never be tracked with version control, and some files that depend more on personal preference. Deciding which files to track is another topic that different people take different approaches to, but there are some rules that are typically followed: \n\n- track source files that you've written (such as R scripts, shell scripts, LaTeX files, etc) \n- track configuration files (such as .gitignore) that tell your tools how to interact with this repository\n- do not track intermediate files (such as log files), these are files that are generated automatically during a certain part of your workflow but are not needed on their own\n- sometimes track derived products (such as intermediate data, figures, or reports)\n  - this depends if you would like a copy of these products to live on GitHub\n  - this also depends on how you want other people to interact with figures or reports: do you want them to be able to view or download them from GitHub, or do you want them to download your data and scripts from GitHub and generate the outputs for themselves? \n- do not track large data files that never change (we'll explain this more below)\n- typically avoid tracking binary files (although there are exceptions)\n\n<details> <summary> Binary files </summary>\n\nFrom a Git perspective, files are either text files or binary files. Text files are human-readable. They work nicely with Git because they can be represented in terms of differences between versions. In contrast, binary files are readable by certain programs but are not human-readable. They cannot be represented in terms of diffs, and therefore a new version of the file is saved at each commit. Examples of binary files are images (.png, .jpeg), word and excel files (.doc, .xlsx) and PDFs (.pdf). Tracking many binary files with Git can eventually slow down Git operations.  \n\n</details>\n\n#### How to use the .gitignore file\n\nThe best way to avoid tracking a file is to add it to your {{< glossary \".gitignore\">}} file. If a file or folder is included in your .gitignore file, it will not be staged when you use the command `git add .`. \n\nIf you open an RStudio project for a Git-tracked repository, you'll have a .gitignore file that looks similar to the following:\n\n```\n# History files\n.Rhistory\n.Rapp.history\n\n# Session Data files\n.Rdata\n.RDataTmp\n\n# User-specific files\n.Ruserdata\n\n# RStudio files\n.Rproj.user/\n```\n\nIf you would like Git to avoid tracking a file called \"large_data.csv\", which lives in a folder called \"data\", you would add the following line to the end of your .gitignore file:\n\n```\ndata/large_data.csv\n```\n\nYou could also tell Git to avoid tracking an entire folder. If you didn't want to track any data from a folder called \"restricted_data\", you would add the following line to your .gitignore file:\n\n```\nrestricted_data/\n```\n\n#### Git and large files\n\nAn important consideration for which files to track is file size. Tracking large files can slow down common Git operations and may eventually exceed GitHub's [repository limits](https://docs.github.com/en/repositories/creating-and-managing-repositories/repository-limits). GitHub recommends that the maximum size of a single object being pushed to GitHub be 1MB, and enforces this size limit at 100 MB. For binary files or moderately large files that still need version control, Git Large File Storage (often referred to as Git LFS) is an option. Git LFS stores large files outside the main repository while preserving version tracking. You can read more about Git LFS [here](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage). \n\nHowever, large data files or results that are not expected to change over time should generally not be tracked with Git at all. Instead, they are better stored in dedicated research data repositories such as [figshare](https://figshare.com) or [Zenodo](https://zenodo.org), which are designed for long-term storage, sharing, and citation. If data files are not tracked by Git or Git LFS, and are therefore not included in the GitHub repository, it is important for the repository to contain download instructions for these data files for other users who may want to run the code and reproduce results. The README file is a good place to include these download instructions. \n\n***\n\n\n<!--\nDescribe the data to be analyzed and where it came from.\nYou may want to include a table about file or variable info.\n-->\n\n# **What are the data?**\n***\n\nIn this case study, we will investigate data about samples from [this meta-analysis](https://www.tandfonline.com/doi/full/10.1080/19490976.2021.1911571) of mother and infant gut {{< glossary \"microbiome\">}} studies. Wang et al. identified a set of eight studies that collected mother and infant gut microbiome samples {{< glossary \"longitudinal\" display=\"longitudinally\">}} and performed metagenomic sequencing. These eight studies collectively include 1,496 samples, representing 368 individuals. The variables that we will use to answer our questions include:\n\nVariable | Details\n-------- | -------\n**Study** | Original study the sample comes from \n**SampleID** | ID for sample (unique ID for each combination of person and time point)\n**PersonID** | ID for participant the sample came from (unique ID for each person in the study, shared across time points)\n**Category** | Either \"mother\" or \"infant\"\n**Sampling from papers** | Sampling time frame described in paper \n**Sampling, day** | Day after birth that the sample was collected on\n\n\n\n<!--\nDescribe any limitations that exist in this analysis whether it be due to the data itself, methods used, nature of the topic, etc.\nYou can list more than 2\nSee the following example from a previous case study: https://www.opencasestudies.org/ocs-bp-opioid-rural-urban/#Limitations\n-->\n\n# **Limitations**\n***\n\nThere are some important considerations regarding this data analysis to keep in mind:\n\n1. In the original studies included in this {{< glossary \"meta-analysis\">}}, some studies describe sampling date in terms of days, and some in terms of weeks or months. Although this is converted into days in the variable `Sampling, day`, time has been measured in finer resolution for some studies compared to others. \n2. In this analysis we are only comparing the original studies based on the number of samples they have and when they collected their samples. There are several other ways we may want to compare these cohorts to understand how comparable they are, including based on measured information (like maternal age, mode of delivery, birth weight, maternal antibiotic use, etc.) as well as unmeasured information. \n\nThere are also limitations of version control: \n\n1. Git does not automatically make commits for you. Any work that you have locally that you have not staged and committed is not under version control. As a version control user, you need to make commits in order to create a record of changes over time. \n  1. Additionally, the quality of the commit messages matters. Poor commit messages will limit your ability to understand why you made certain changes when looking back at the commit history of your analysis. \n1. As described in the [scientific project organization section](https://www.opencasestudies.org/ocs-bio-version-control/#scientific-project-organization), version control is not ideal for large binary files. \n1. Git and GitHub are currently the most widely used tools for version control, with extensive documentation and active development. However, like any software tool, their long-term availability is not guaranteed. While the principles of version control will remain integral to reproducible research, the specific technologies used to implement these principles may evolve over time. \n\n***\n\n\n<!--\nList any important bioethics considerations when performing an analysis like this or working with data like this.\n\nSee doi: 10.1007/s41649-019-00099-x and https://depts.washington.edu/bhdept/ethics-medicine/bioethics-topics/articles/principles-bioethics for principles and considerations.\nExamples may include: how identifiable (or re-identifiable) is your data? cell lines or consent? specific considerations for a specific population?\n-->\n\n\n# **Ethical Considerations**\n***\n\nThere are some important ethical considerations when working with version control, as well as with health related data in general and when collaborating on scientific projects. \n\n1. When hosting data, code, and results on {{< glossary \"GitHub\">}}, **make sure to never include personally identifiable information (PII) or protected health information (PHI) in a repository** (even private repositories are not truly private or secure and are not appropriate places to store PII or PHI). This includes names, dates of birth, medical records and diagnosis, lab results, identifiable genomic sequencing data, as well as other types of data. You can read more about PII and PHI in [this course](https://hutchdatascience.org/Ethical_Data_Handling_for_Cancer_Research/data-privacy.html#pii-personal-identifiable-information) about ethical data handling. For more general information about data management, you can explore [this course](https://hutchdatascience.org/Proactive_Data_Management_and_Sharing/). \n\n    a. If you do commit sensitive information to a version controlled repository on GitHub, it is **not sufficient to simply remove the file, commit the changes, and push again**. If you do this, any files with sensitive information will be part of a commit, and will therefore be a part of the history of the repository. While there are ways to remove sensitive information from a local commit, and from a GitHub repository, these are more complicated operations and will affect collaborators that work on the repository with you. It is important to inform collaborators of the sensitive information that has been committed.\n  \n1. Make sure to keep comprehensive documentation for scientific projects to avoid losing track of which data generated a set of results or figure, or which version of a software you used in an analysis. Reproducible science is ethical science: without a transparent and well-documented process, others in the scientific community cannot easily verify or trust your results.\n1. For projects with large teams, it can be challenging to track individual contributions. {{< glossary \"Version control\">}} histories can be helpful to see who worked on each component on an analysis, in order to fairly acknowledge each contributor’s work. You can read [this paper](https://link.springer.com/article/10.1007/s11948-014-9562-8) for more ethical considerations related to large team science. \n1. When performing a {{< glossary \"meta-analysis\">}} such as the one described in this case study, it is important to be transparent about inclusion and exclusion criteria for studies and for individual observations within studies. Criteria should be determined before analysis, to avoid choosing studies that will support a desired conclusion. It is also important to properly cite the original studies and recognize the groups that collected the data. \n\n***\n\n<!--\nConsider incorporating a checklist of statements that learners should answer/discuss for every case study for bioethics principles.\n-->\n\n\n::: {.content-hidden unless-meta=\"include-sections.data-import\"}\n# **Packages and Setup**\n***\n\nBefore we get into the coding, we want to describe the R packages that we'll use in this case study, or that are used in other scripts contained in our repository:\n\n\n::: {.cell}\n\n:::\n\n\nPackage    | Use | Where this packages is used  \n---------- |------------- | ----------------------------\n[here](https://here.r-lib.org) | To construct file paths within folders | [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)\n[readxl](https://readxl.tidyverse.org){target=\"_blank\"}      | To read excel files into R | [Data import](https://www.opencasestudies.org/ocs-bio-version-control/#data-import)\n[dplyr](https://dplyr.tidyverse.org){target=\"_blank\"}      | To combine and manipulate data tables | [Data import](https://www.opencasestudies.org/ocs-bio-version-control/#data-import), [Data exploration](https://www.opencasestudies.org/ocs-bio-version-control/#data-exploration), [Data wrangling](https://www.opencasestudies.org/ocs-bio-version-control/#data-wrangling), [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization), [Data analysis](https://www.opencasestudies.org/ocs-bio-version-control/#data-analysis)\n[ggplot2](https://ggplot2.tidyverse.org) | To visualize data | [Data visualization](https://www.opencasestudies.org/ocs-bio-version-control/#data-visualization)\n[stringr](https://stringr.tidyverse.org) | To manipulate strings | [Data wrangling](https://www.opencasestudies.org/ocs-bio-version-control/#data-wrangling)\n\n\nThe first time we use a function, we will use the `::` to indicate which package we are using. Unless we have overlapping function names, this is not necessary, but we will include it here to be informative about where the functions we will use come from.\n\nThree of these packages, `dplyr`, `ggplot2`, and `stringr` are part of the [tidyverse suite of packages](https://tidyverse.org). The `tidyverse` includes eight packages that can easily be used together and share data structures and syntax. While each of the packages can be installed or loaded separately (as we do above), they can be installed or loaded all at once using `install.packages(\"tidyverse\")` or `library(tidyverse)`. \n\n***\n\n<!--\nUpdate the file paths as needed throughout\n-->\n\n<!--\nAt the end of this section, save incremental data so that users can pause and come back later\n-->\n\n# **Data Import**\n***\n\nNow that you have set up this project with {{< glossary \"Git\">}} and {{< glossary \"GitHub\">}}, you can start working on the study comparison in R. Open RStudio or Positron or your preferred R IDE to the \"infant_gut_analysis\" folder. We will start by taking a look at the data. Take a look at the {{< glossary \"README\">}} file to determine which file contains commands that can read in the raw data. Open this file and run the code. \n\n<details> <summary> Click here to see the code included in this file. </summary>\n\n::: {.rcode}\n```r\nlibrary(readxl) # for reading data from supplementary table\nlibrary(dplyr) # for combining data across studies \n\n# read tabs for each study from Table S1 from Wang et al. supplementary \n# information, saved as \"meta_analysis_metadata.xlsx\"\nstudy_data <- lapply(3:10, function(i) {\n  readxl::read_xlsx(\"raw_data/Table S1.xlsx\", sheet = i)\n}) \n\n# set all variables as characters in order to combine data across studies\n# original data had some variables in different data types across studies\nstudy_data_clean <- lapply(study_data, function(df) {\n  df %>% dplyr::mutate(dplyr::across(dplyr::everything(), as.character))\n})\n\n# combine lists for each study into a single data frame\nsample_metadata <- dplyr::bind_rows(study_data_clean)\n\n# save data frame as a .rda file\nsave(sample_metadata, file = \"processed_data/sample_metadata.rda\")\n```\n:::\n\n</details>\n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nHow many observations are included in our data set? How many variables are included in our data set? \n<details> <summary> Hint </summary>\n\nData is imported in the file \"01_pull_study_data.R\". You can find out how many rows are in a data frame with the function `nrow(name_of_data_frame)`. You can find out how many columns are in a data frame with the function `ncol(name_of_data_frame)`. \n\n</details>\n<details><summary>Answer</summary>\n\n\n::: {.cell}\n\n:::\n\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(sample_metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1499\n```\n\n\n:::\n\n```{.r .cell-code}\nncol(sample_metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20\n```\n\n\n:::\n:::\n\n:::\n\nThere are 1,499 observations and 20 variables in the data frame.\n</details>\n::::\n:::\n\n***\n\n\n:::\n\n::: {.content-hidden unless-meta=\"include-sections.data-exploration\"}\n\n<!--\nUpdate the file paths as needed throughout\n-->\n\n<!--\nNot all case studies will need a Data Exploration subsection\n-->\n\n<!--\nAt the end of this section, save incremental data (if changes were made) so that users can pause and come back later\n-->\n\n# **Data Exploration**\n***\n\n\n::: {.cell}\n\n:::\n\n\nNow that you've imported the data, let's take a look at it. We'll use the function `glimpse()`, from the `dplyr` package that we've already been working with. This function shows the first several observations from each column of our dataset.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(sample_metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,499\nColumns: 20\n$ Study                                          <chr> \"AsnicarF_2017\", \"Asnic…\n$ Run                                            <chr> \"SRR4052021\", \"SRR40520…\n$ SampleID                                       <chr> \"MV_FEI1_t1Q14\", \"MV_FE…\n$ PersonID                                       <chr> \"1\", \"1\", \"2\", \"2\", \"3\"…\n$ Type                                           <chr> \"stool\", \"stool\", \"stoo…\n$ Category                                       <chr> \"infant\", \"mother\", \"in…\n$ `Maternal age`                                 <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Maternal body mass index before pregnancy`    <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Maternal antibiotics before delivery`         <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Maternal intrapartum antibiotics`             <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Sampling from papers`                         <chr> \"3mo\", \"3mo\", \"3mo\", \"3…\n$ `Sampling, day`                                <chr> \"90\", \"90\", \"90\", \"90\",…\n$ `Feeding regimen`                              <chr> \"combined\", \"NA\", \"brea…\n$ `Postnatal antibiotic intervention in infants` <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ Gender                                         <chr> \"female\", \"female\", \"ma…\n$ `Mode of delivery`                             <chr> \"vaginal\", \"vaginal\", \"…\n$ `Caesarean-section type`                       <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Gestational age`                              <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ `Birth weight`                                 <chr> \"NA\", \"NA\", \"NA\", \"NA\",…\n$ Country                                        <chr> \"ITA_1\", \"ITA_1\", \"ITA_…\n```\n\n\n:::\n:::\n\n:::\n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nAs we described in the [\"What are the data?\" section](https://www.opencasestudies.org/ocs-bio-version-control/#what-are-the-data), the variables that we will use in our analysis are `Study`, `SampleID`, `PersonID`, `Category`, `Sampling from papers`, and `Sampling, day`. Based on the output of the `glimpse()` function, which if any of these variables will we want to work with as a numeric data type as opposed to a character data type? \n<details> <summary> Hint </summary>\n\nNumeric data types are used for data that we'd like to do math with (such as `4` or `3.14`). Character data types are used for data in which we record a word or a series of words, and don't need to do any mathematical equations (such as `\"apple\"` or `\"treatment group\"`). Character data are enclosed in quotes. \n\n</details>\n<details><summary>Answer</summary>\n\nThe variable `Sampling, day` is saved as a character, however seems to contain numerical data. In the [Data Wrangling section](https://www.opencasestudies.org/ocs-bio-version-control/#data-wrangling) we will recode `Sampling, day` as a numeric variable. \n\n</details>\n::::\n:::\n\n\n\n***\n\n<!--\nUse this section to walk through any exploration of the dataset conducted pre-analysis.\n-->\n\n\n:::\n\n::: {.content-hidden unless-meta=\"include-sections.data-wrangling\"}\n\n<!--\nUpdate the file paths as needed throughout\n-->\n\n<!--\nSome case studies may wish to merge Data Exploration with this Wrangling subsection\n-->\n\n<!--\nAt the end of this section, save incremental data so that users can pause and come back later\n-->\n\n# **Data Wrangling**\n***\n\nData wrangling includes cleaning data to fix mistakes and reorganizing data to make it easier to use in visualizations and analyses. Again, use the {{< glossary \"README\">}} to identify which file contains commands that wrangle the data. Open this file and run the code. \n\n<details> <summary> Click here to see the code included in this file. </summary>\n\n::: {.rcode}\n```r\nlibrary(dplyr) # for data manipulation\nlibrary(stringr) # for working with strings\n\n# load data that we saved in data_import\nload(\"processed_data/sample_metadata.rda\")\n\n# clean data\nclean_metadata <- sample_metadata %>%\n  # remove all rows in data that are missing sample ID\n  dplyr::filter(!is.na(SampleID)) %>% \n  # clean study name to only include last name of first author\n  mutate(Study = \n           # remove _year from study name\n           stringr::str_remove(Study, \"\\\\_.*\") %>% \n           # remove first name initial from study name\n           stringr::str_remove_all(\"(?<=.)[A-Z]\")) %>% \n  # remove spaces from names of variables \n  dplyr::rename(sampling_paper = `Sampling from papers`, \n         sampling_day = `Sampling, day`) %>%\n  # make sampling_day a numeric variable\n  mutate(sampling_day = as.numeric(sampling_day)) \n\n# in Yassour study, sample IDs are not unique to samples \n# first inspect this to confirm\nclean_metadata %>%\n  filter(Study == \"Yassour\") %>%\n  dplyr::select(Study, Category, SampleID, sampling_day) %>%\n  head()\n\n# create new unique sample IDs for Yassour study\nclean_metadata <- clean_metadata %>%\n  # check if study is Yassour\n  mutate(SampleID = ifelse(Study == \"Yassour\", \n                           # if so, combine sample ID and sampling day\n                           paste0(SampleID, sampling_day),\n                           # if not, leave sample ID as is \n                           SampleID)) \n\n# confirm that we've fixed this problem\nclean_metadata %>%\n  filter(Study == \"Yassour\") %>%\n  select(Study, Category, SampleID, sampling_day) %>%\n  head()\n\n# two studies (Parnanen and Yassour) took samples \n# from mothers during pregnancy\n# for these samples, `sampling_day` represents sampling day \n# since start of pregnancy, unlike all other samples for which \n# `sampling_day` represents sampling day since birth\nids_before_birth <- clean_metadata %>%\n  # identify these specific samples\n  filter(Category == \"mother\",\n         Study == \"Parnanen\" & sampling_paper == \"32WK\" |\n           Study == \"Yassour\" & sampling_paper == \"Gest\") %>%\n  # get sample ids for these samples\n  dplyr::pull(SampleID) \nclean_metadata <- clean_metadata %>%\n  # add `sampling_before_birth` variable, and set to TRUE\n  # for these specific samples we identified \n  mutate(sampling_before_birth = ifelse(SampleID %in% ids_before_birth,\n                                        TRUE, FALSE))\n\n# save cleaned data\nsave(clean_metadata, file = \"processed_data/clean_sample_metadata.rda\")\n```\n:::\n\n</details>\n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nWhat are the earliest and latest time points that samples were taken, relative to an infant's birth date, in the data set?  \n\n<details> <summary> Hint </summary>\n\nData are wrangled in the file \"02_wrangle_data.R\". You can use the functions `max()` and `min()` to get the maximum and minimum values in a vector. The variable in the cleaned data set that gives the sampling day relative to the infant's birth date is called `sampling_day`. \n\n</details>\n<details><summary>Answer</summary>\n\n\n::: {.cell}\n\n:::\n\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(clean_metadata$sampling_day, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(clean_metadata$sampling_day, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 480\n```\n\n\n:::\n:::\n\n\nThe earliest day that a participant was sampled after birth was 0, and the latest day was 480. \n\n:::\n\n\n</details>\n::::\n:::\n\n***\n\n\n:::\n\n::: {.content-hidden unless-meta=\"include-sections.data-viz\"}\n\n\n# **Data Visualization**\n***\n\nWe will now generate visualizations to compare the {{< glossary \"meta-analysis\">}} study cohorts.\n\nFirst, we will make sure that we are on the correct branch. We want to use a development branch for this analysis, which we will request to merge back into the main branch once the analysis is ready. We already created the branch \"study_comparison\" in the [introduction to Git and GitHub section](https://www.opencasestudies.org/ocs-bio-version-control/#branches), so we just need to make sure that we are working on that branch.\n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\n- In the upper panel, under \"Current Branch\", look to see if it says the current branch is \"study_comparison\" or \"main\" or something else.\n  - If it says \"study_comparison\", then you are already working on the correct branch.\n  - If it says \"main\", then you can click the drop-down button next to \"Current Branch\" and select \"study_comparison\".\n    - If \"study_comparison\" does not appear, you can click the \"New Branch\" button to create it. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f94a4bdf40_0_170.png){fig-align='center' fig-alt='Creating first repository' width=100%}\n:::\n:::\n\n\n#### Command line \n\nOpen the command line and navigate to your repository. Use the `git branch` command. \n\n:::: {.shell}\n```bash\ngit branch\n```\n::::\n\nThis should list the branches for your repository, with the current branch highlighted and marked with an asterisk (*). If the highlighted branch is \"study_comparison\", then you are already working on the correct branch. If the highlighted branch is \"main\" or something else, you can switch over to \"study_comparison\" using the `git checkout` command. \n\nIf \"study_comparison\" appears in your list of branches, you can move to it with the following command:\n\n:::: {.shell}\n```bash\ngit checkout study_comparison\n```\n::::\n\nHowever, if \"study_comparison\" doesn't appear in your list of branches, you can create it with `git checkout -b`. \n\n:::: {.shell}\n```bash\ngit checkout -b study_comparison\n```\n::::\n:::\n\nBecause this is a new component of the analysis, we will create a new file in the \"infant_gut_analysis\" folder for this code. \n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nReproducibility considerations\n::::\n::::{.inner_block}\nThere are different types of files that you can create to run R code. The most basic file is a .R script, which is used for the scripts that we ran in the data import and wrangling sections: \"01_pull_study_data.R\" and \"02_wrangle_data.R\". An R script assumes that all contents are R code, except for comments (which are preceded by `#`). \n\nAnother file type is a notebook-style document, which combines text components with code components. The code is broken into pieces, which are referred to as \"code chunks\". Two common types of these files are R Markdown files (.Rmd) and quarto files (.qmd). These files can be rendered, which means that all code chunks are run in order (typically in a fresh R session), and any output (calculations, tables, plots) is included in the resulting document. These notebook-style formats also make it easier to explain what each step of an analysis is doing, improving both readability and reproducibility by clearly linking code, output, and interpretation in a single document.\n::::\n:::\n\nTo start, we will create a new quarto document and call it \"03_visualize_study_cohorts.qmd\". Make sure to give your quarto document an appropriate title. \n\nIn this section, we will go through the steps to make two visualizations to compare the study cohorts. As you go, include the relevant code (as well as explanations of what the code is doing) into your quarto document. When you are done, you or someone else with access to the data and your document, should be able to run the code and create the visualizations. \n\nIn your quarto document, you should start by making a code chunk to load the required packages. \n\n<details>\n<summary>Adding a code chunk to a quarto file</summary>\n\n::: {.panel-tabset}\n\n#### Manually\n\nTo add a new R code chunk, go to a new line and enter: ```{r}\n\nThen, type your code, starting on the following line. To end a code chunk, go to another new line and enter: ```\n\n#### In RStudio\n\nYou can also add a code chunk in RStudio by clicking the button green button with a plus sign and a \"c\", below the open file names. Other options include navigating to \"Code\" -> \"Insert Chunk\" or using a keyboard shortcut: `Ctrl + Alt + I` in Windows and Linux, and `Cmd + Option + I` on Mac. \n\n#### In Positron\n\nYou can also add a code chunk in Positron by clicking the icon that shows an arrow pointing towards to two vertical boxes. There is a keyboard shortcut to add a code chunk: `Ctrl + Shift + I` in Windows and Linux, and `Cmd + Shift + I` on Mac. \n\n:::\n</details>\n\n**Include this code in your .qmd file**, to load the packages that we'll need. \n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n:::\n\nNext, we will load the wrangled data. We will use the function `here()`, which creates relative file paths. \n\n<details>\n<summary>More information about the `here()` function:</summary>\nThe `here()` function creates file paths that always start from the main project folder (the top-level folder that contains all of your project files). In a Git-tracked repository, this is the folder that contains the `.git` directory, which was created when you initialized the repository. However, there are other ways here can determine where to start the path, including the directory with an .Rproject file (if you are using one), see this [list of conditions for the starting directory](https://here.r-lib.org/reference/here.html) for more information.  Using relative file paths (i.e., paths that only reference folders within your project) makes your code more portable and easier for collaborators to run. Importantly, the `here()` function creates these relative paths in a way that is compatible with different kinds of operating systems which have different path requirements. In contrast, absolute file paths depend on the specific file structure of your personal computer and will not necessarily work on other machines.\n</details>\n\nWe want to load data from the file \"clean_sample_metadata.rda\", contained within the \"processed_data\" folder. **Include this code in your .qmd file** to load the data.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here::here(\"processed_data\", \"clean_sample_metadata.rda\"))\n```\n:::\n\n:::\n\nNow that you have created a new file and loaded packages and data, this is a good time to track this new file and {{< glossary \"commit\">}} your work. \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNavigate back to {{< glossary \"GitHub Desktop\">}}. You should see your new file name \"03_visualize_study_cohorts.qmd\" with a green plus next to it, meaning that this is a new file. The check in the checkbox means that this file is staged. Add an appropriate commit message and commit this file. \n\n#### Command line \n\nOpen the {{< glossary \"command line\">}} and navigate to your repository. Recall that you can stage the new file (tell Git to track it with):\n\n:::: {.shell}\n```bash\ngit add 03_visualize_study_cohorts.qmd\n```\n::::\n\nNext, add a commit with an appropriate commit message. \n\n:::: {.shell}\n```bash\ngit commit -m \"Add new file '03_visualize_study_cohorts'\"\n```\n::::\n\n:::\n\nNow that we've started tracking our work with Git, let's start by considering the first question: how do these studies compare in terms of the number of observations? \n\nUse the `dplyr` functions `group_by()` and `count()` to view the number of observations per study.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_metadata %>%\n  dplyr::group_by(Study) %>%\n  dplyr::count(name = \"total\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n# Groups:   Study [8]\n  Study    total\n  <chr>    <int>\n1 Asnicar     16\n2 Backhed    392\n3 Chu         27\n4 Ferretti   102\n5 Parnanen    64\n6 Shao       588\n7 Wampach     49\n8 Yassour    258\n```\n\n\n:::\n:::\n\n:::\n\n<details>\n<summary>A note on the pipe operator `%>%`</summary>\nThe pipe operator `%>%` chains R commands together. It takes the preceding object and inputs it as the first argument to the function that follows it. It often is used to make code more readable and to avoid using intermediate objects or nested functions. The code above is equivalent to both of these expressions:\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_data <- group_by(clean_metadata, Study)\ncount(grouped_data, name = \"total\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n# Groups:   Study [8]\n  Study    total\n  <chr>    <int>\n1 Asnicar     16\n2 Backhed    392\n3 Chu         27\n4 Ferretti   102\n5 Parnanen    64\n6 Shao       588\n7 Wampach     49\n8 Yassour    258\n```\n\n\n:::\n:::\n\n:::\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(group_by(clean_metadata, Study))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n# Groups:   Study [8]\n  Study        n\n  <chr>    <int>\n1 Asnicar     16\n2 Backhed    392\n3 Chu         27\n4 Ferretti   102\n5 Parnanen    64\n6 Shao       588\n7 Wampach     49\n8 Yassour    258\n```\n\n\n:::\n:::\n\n:::\n\nThe pipe operator that we use, `%>%`, is part of the `magrittr` and `dplyr` R packages. There is also a pipe operator in base R, `|>`. In most cases, these two pipe operators will work equivalently. \n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_metadata |>\n  group_by(Study) |>\n  count(name = \"total\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n# Groups:   Study [8]\n  Study    total\n  <chr>    <int>\n1 Asnicar     16\n2 Backhed    392\n3 Chu         27\n4 Ferretti   102\n5 Parnanen    64\n6 Shao       588\n7 Wampach     49\n8 Yassour    258\n```\n\n\n:::\n:::\n\n:::\n\n</details>\n\nWe can see that there is quite the spread of study sizes. Let's also break this down by whether observations are from infants vs mothers. Whether the observation comes from an infant or a mother is contained in the variable `Category`.\n\n**Your turn**: Modify the code above to count the number of observations by `Study` and by `Category`, and save the results as a data frame named `sample_counts`. **Add this code to your .qmd file.**\n\nThe data frame should look like this:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 3\n# Groups:   Study, Category [16]\n   Study    Category total\n   <chr>    <chr>    <int>\n 1 Asnicar  infant       8\n 2 Asnicar  mother       8\n 3 Backhed  infant     294\n 4 Backhed  mother      98\n 5 Chu      infant      12\n 6 Chu      mother      15\n 7 Ferretti infant      81\n 8 Ferretti mother      21\n 9 Parnanen infant      32\n10 Parnanen mother      32\n11 Shao     infant     410\n12 Shao     mother     178\n13 Wampach  infant      35\n14 Wampach  mother      14\n15 Yassour  infant     152\n16 Yassour  mother     106\n```\n\n\n:::\n:::\n\n\n<details>\n<summary>View code:</summary>\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_counts <- clean_metadata %>%\n  group_by(Study, Category) %>%\n  count(name = \"total\")\nsample_counts\n```\n:::\n\n:::\n</details>\n\nNow that we've looked at this data in a table format, let's make a plot so that we can compare this data visually. We'll make a bar plot, with separate bars for each study and for observation category (infant vs mother). **Include this code in your .qmd document** to make a bar plot.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_counts %>%\n  ggplot2::ggplot(ggplot2::aes(x = Study, y = total, fill = Category)) +\n  ggplot2::geom_col(position = ggplot2::position_dodge())\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n:::\n\nWhile this plot looks good, it would be visually easier to compare if the studies were ordered by the number of observations. We can make a vector that orders the studies from the least observations to the most observations by using the `dplyr` functions `group_by()`, `summarise()`, `arrange()`, and `pull()`. \n\n<details>\n<summary>More information about these `dplyr` functions:</summary>\n\n| `dplyr` function | operation | \n| ---------------- | --------- |\n| `group_by()` | groups rows by a variable | \n| `summarise()` | computes table of summaries | \n| `arrange()` | sorts rows by one or more variables | \n| `pull()` | pulls a variable from the data frame as a vector|\n\n</details>\n\n**Include this code in your .qmd document** to make a new vector for the desired study order.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_order <- sample_counts %>%\n  group_by(Study) %>%\n  dplyr::summarise(total_both = sum(total)) %>%\n  dplyr::arrange(total_both) %>%\n  pull(Study)\nstudy_order\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Asnicar\"  \"Chu\"      \"Wampach\"  \"Parnanen\" \"Ferretti\" \"Yassour\"  \"Backhed\" \n[8] \"Shao\"    \n```\n\n\n:::\n:::\n\n:::\n\nWe can now order the bar plot by increasing sample size. **Include this code in your .qmd document** to make the bar plot with increasing bar heights.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_counts %>%\n  mutate(Study = factor(Study, levels = study_order)) %>%\n  ggplot(aes(x = Study, y = total, fill = Category)) +\n  geom_col(position = position_dodge()) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n:::\n\nFinally, we can update the colors of the plot and add labels. We will use the function `scale_fill_viridis_d()` to use colors that are more color-deficiency friendly (more information about these color scales can be found [in this resource](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html). **Include this code in your .qmd document** to refine your bar plot.\n \n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_counts %>%\n  mutate(Study = factor(Study, levels = study_order)) %>%\n  ggplot(aes(x = Study, y = total, fill = Category)) +\n  geom_col(position = position_dodge()) +\n  ggplot2::scale_fill_viridis_d() + \n  ggplot2::theme_minimal() + \n  ggplot2::labs(y = \"Number of samples\",\n       x = \"Study\",\n       title = \"Number of Samples by Study and Category\") + \n  ggplot2::theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n:::\n\nWe will now use `ggsave()` to save this plot in the figures folder. **Include this code in your .qmd document** to save this bar plot with the file name \"study_sizes_by_category.png\" within the \"figures\" folder.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggsave(\"figures/study_sizes_by_category.png\", height = 6, width = 9)\n```\n:::\n\n:::\n\nThis is another great time to commit your current work.\n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNavigate back to GitHub Desktop. You should see that \"03_visualize_study_cohorts.qmd\" now has an orange box next to it (signaling that this file has been modified) and that \"figures/study_sizes_by_category.png\" has been added (which is signaled by the green plus sign next to it). Make sure that both of these have checks in the checkboxes to the left of the filenames, which indicates that they are staged. Add an appropriate commit message and commit these files. \n\n#### Command line \n\nEven though Git is already tracking \"03_visualize_study_cohorts.qmd\", we still need to use `git add` to tell Git to stage this file for this commit. We will also need to start tracking \"figures/study_sizes_by_category.png\". We can stage multiple files at once by listing them with spaces between. \n\n:::: {.shell}\n```bash\ngit add 03_visualize_study_cohorts.qmd figures/study_sizes_by_category.png \n```\n::::\n\nNext, add a commit with an appropriate commit message. \n\n:::: {.shell}\n```bash\ngit commit -m \"Add plot of study sizes to '03_visualize_study_cohorts' and save plot in figures folder.\"\n```\n::::\n\n:::\n\nNext we will consider the second question: how do these studies compare in terms of when they took samples after the birth of the infants? You may have noticed in the script \"02_wrangle_data.R\" that two studies took samples from mothers during pregnancy. This information is contained in the variable `sampling_before_birth`. We would like to exclude these observations from our plots, because their `sampling_day` is counted from the beginning of pregnancy and not since birth. \n\n**Your turn**: create a data frame `observations_after_birth` that does not include these observations that were taken before birth. **Include this code in your .qmd document.**\n\n<details>\n<summary>Hint:</summary>\n::: {.rcode}\nThe function `filter()` will remove rows that match a certain logical condition. \n:::\n</details>\n\n<details>\n<summary>View code:</summary>\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nobservations_after_birth <- clean_metadata %>%\n  filter(!sampling_before_birth) \n```\n:::\n\n:::\n</details>\n\nNow, we will make a histogram of sampling day, where we separate the data by `Category` and `Study`. There are multiple ways to do this, but we will color the bars by `Category` and then use `facet_wrap()` to make separate panels for each study. **Include this code in your .qmd document** to make histograms of sampling day for each study. \n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nobservations_after_birth %>%\n  ggplot(aes(x = sampling_day, fill = Category, group = Category)) +\n  ggplot2::geom_histogram(position = position_dodge(), bins = 20) +\n  ggplot2::facet_wrap(~Study, scale = \"free_y\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 7 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n:::\n\n<details>\n<summary>More information about this warning message.</summary>\n`ggplot` will give you warning messages when there are data in the dataframe that it cannot include in a plot due to missing information. In this warning, we can see that 7 observations in the data (representing samples taken) cannot be plotted because of non-finite values. Typically, this means there are observations with missing data. We can investigate what is missing with the following:\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nobservations_after_birth %>%\n  # only keep rows that have NA values for Study, sampling_day, or Category\n  filter(is.na(Study) | is.na(sampling_day) | is.na(Category)) %>% \n  # view a smaller subset of variables\n  select(Study, SampleID, PersonID, sampling_day, Category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  Study   SampleID  PersonID sampling_day Category\n  <chr>   <chr>     <chr>           <dbl> <chr>   \n1 Backhed 201_4M    201                NA infant  \n2 Backhed 229_M     229                NA mother  \n3 Backhed 229_B     229                NA infant  \n4 Backhed 544_B     544                NA infant  \n5 Backhed 624_B     624                NA infant  \n6 Backhed 633_B     633                NA infant  \n7 Shao    C01831_NA C01831             NA infant  \n```\n\n\n:::\n:::\n\n:::\n\nHere we can see that there are 6 observations from the Backhed study and one observation from the Shao study for which `sampling_day` is missing. Therefore, these observations cannot be included in the plot.\n\n</details>\n\nNotice that because we set `scale = \"free_y\"` in the `facet_wrap()`, each of the y-axes of the panels is different. Let's order the studies in the same order that we used in the bar plot earlier. We will also update the theme, switch to color-deficiency friendly colors, and add axes labels. **Include this code in your .qmd document** to order the studies and refine your histograms. \n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nobservations_after_birth %>%\n  mutate(Study = factor(Study, levels = study_order)) %>%\n  ggplot(aes(x = sampling_day, fill = Category, group = Category)) +\n  geom_histogram(position = position_dodge(), bins = 20) +\n  facet_wrap(~Study, scale = \"free_y\") +\n  labs(x = \"Days since birth at sampling\",\n       y = \"Count\",\n       title = \"Distribution of sampling day across studies\") + \n  scale_fill_viridis_d() + \n  theme_minimal() + \n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 7 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n:::\n\nFinally, we will save this plot in the figures folder. **Include this code in your .qmd document** to save this plot with the file name \"sampling_timepoints.png\" within the \"figures\" folder.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"figures/sampling_timepoints.png\", height = 6, width = 9)\n```\n:::\n\n:::\n\nNow that we have two plots, go back through your file \"03_visualize_study_cohorts.qmd\" to make sure that it contains all relevant code to make these two plots, and that there are explanations before each code chunk. \n\nOnce you've done this, make another commit for these edits. \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNavigate back to GitHub Desktop. Stage \"03_visualize_study_cohorts.qmd\" and \"figures/sampling_timepoints.png\", add an informative commit message, and commit these files. \n\n#### Command line \n\nFirst, stage \"03_visualize_study_cohorts.qmd\" and \"figures/sampling_timepoints.png\".\n\n:::: {.shell}\n```bash\ngit add 03_visualize_study_cohorts.qmd figures/sampling_timepoints.png \n```\n::::\n\nNext, add a commit with an appropriate commit message. \n\n:::: {.shell}\n```bash\ngit commit -m \"Add plot of sampling time points to '03_visualize_study_cohorts' and save plot in figures folder.\"\n```\n::::\n\n:::\n\nGreat job! You have now made two plots to compare the study designs of the studies within the meta-analysis, and made several commits with informative messages that create a history of this analysis. \n\n***\n\n\n:::\n\n::: {.content-hidden unless-meta=\"include-sections.data-analysis\"}\n\n# **Data Analysis**\n***\n\nNow, we're going to put our evidence together to draw some conclusions about the study designs of studies included in this meta-analysis. \n\nFirst, recall the two plots that we made.\n\n\n::: {.cell}\n\n:::\n\n\n::: {.panel-tabset}\n\n#### Number of samples plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n#### Sampling time points plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n:::\n\nAdditionally, we can make a summary table to have a concise view of some of the important study design features of these studies.\n\n::: {.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_metadata %>%\n  # group data by study and category \n  group_by(Study, Category) %>%\n  # calculate the number of unique people in each study and category\n  summarise(n_person = dplyr::n_distinct(PersonID),\n            # calculate the number of unique samples in each study and category\n            n_sample = n_distinct(SampleID),\n            # calculate the number of unique days at which samples were taken in \n            # each study and category \n            n_time = n_distinct(sampling_paper),\n            # calculate first sampling day for each study and category\n            min_time = min(sampling_day[!sampling_before_birth], na.rm = TRUE),\n            # calculate last sampling day for each study and category\n            max_time = max(sampling_day[!sampling_before_birth], na.rm = TRUE),\n            # report if any samples were taken during pregnancy, and when \n            pregnancy_time = ifelse(any(sampling_before_birth), \n                                    median(sampling_day[sampling_before_birth]),\n                                    NA),\n            .groups = \"drop\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 8\n   Study    Category n_person n_sample n_time min_time max_time pregnancy_time\n   <chr>    <chr>       <int>    <int>  <int>    <dbl>    <dbl>          <dbl>\n 1 Asnicar  infant          5        8      3       90     480              NA\n 2 Asnicar  mother          5        8      3       90     480              NA\n 3 Backhed  infant         98      294     72        0     409              NA\n 4 Backhed  mother         98       98     15        0      20              NA\n 5 Chu      infant         10       12      2        0      42              NA\n 6 Chu      mother         10       15      2        0      42              NA\n 7 Ferretti infant         21       81      5        1     120              NA\n 8 Ferretti mother         21       21      1        0       0              NA\n 9 Parnanen infant         16       32      2       30     180              NA\n10 Parnanen mother         16       32      2       30      30             224\n11 Shao     infant        178      410     58        4     428.             NA\n12 Shao     mother        178      178      1        0       0              NA\n13 Wampach  infant         14       35      4        1       5              NA\n14 Wampach  mother         14       14      1        0       0              NA\n15 Yassour  infant         38      152      5        0      90              NA\n16 Yassour  mother         38      106      3        0      90             189\n```\n\n\n:::\n:::\n\n:::\n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nRecall one of the main questions of this case study: In this meta-analysis of infant git microbiome samples, how do the original studies compare in their sampling designs? Specifically, how do they compare in terms of the number of samples and the sampling timeline?\n\nUse the two plots you've made and the table above to make a few observations that compare and contrast the sampling designs of the original studies. Include these observations at the end of your \"03_visualize_study_cohorts.qmd\" document. \n\n<details><summary>Answer</summary>\n\nPossible observations from the plots: \n\n- Two studies have small samples sizes (Asnicar with 16 samples and Chu with 27 samples), three studies have more moderate sample sizes (Wampach with 49 samples Parnanen with 64 samples, and Ferretti with 102 samples), and three studies have larger sample sizes (Yassour with 258 samples, Backhed with 392 samples, and Shao with 588 samples). \n- Some studies take the same number or similar numbers of samples from mothers and infants (Asnicar, Chu, Parnanen) and other studies take significantly more samples from infants than mothers (Wampach, Ferretti, Yassour, Backhed, and Shao). \n- Wampach sampled only in the first days after birth, Chu, Parnanen, Ferretti, and Yassour sampled only in the first six months since birth, and Asnicar, Backhed, and Shao took samples in the first year and a half since birth. \n- Some studies appear to have sampled at specific time points (Asnicar, Chu, Wampach, Parnanen, and Ferretti) and other studies appear to have sampled at a wider variety of timepoints (Yassour, Backhed, Shao). \n\n</details>\n::::\n:::\n\nSince you've performed the requested analysis, make sure to document any new files in this repository in the README.md file. Specifically, describe what the file \"03_visualize_study_cohorts.qmd\" does, and describe the two plots that are now saved in the figures folder. After doing this, make another commit and {{< glossary \"push\">}} your work. \n\n::: {.panel-tabset}\n\n#### GitHub Desktop \n\nNavigate back to GitHub Desktop. \n\n- [ ] Stage \"03_visualize_study_cohorts.qmd\" and \"README.md\". \n- [ ] Add an appropriate commit message and commit. \n- [ ] Click \"Push origin\", to push these changes that you've made locally to your remote repository. \n\n#### Command line \n\nWe need to first stage \"03_visualize_study_cohorts.qmd\" and \"README.md\".\n\n:::: {.shell}\n\n```bash\ngit add 03_visualize_study_cohorts.qmd README.md\n```\n\n::::\n\nNext, add a commit with an appropriate commit message. \n\n:::: {.shell}\n\n```bash\ngit commit -m \"Draw conclusions and document new files in README\"\n```\n\n::::\n\nFinally, push these changes that you've made locally to your remote repository. Because this is your first time pushing from a new branch, you will need to tell Git where you want to push to, adding the flag `--set-upstream origin branch_name`. \n\n:::: {.shell}\n\n```bash\ngit push --set-upstream origin study_comparison\n```\n\n::::\n\n:::\n\n\n***\n\n\n:::\n\n# **Pull Requests**\n***\n\n## What is a pull request? \n***\n\nRecall that in the initial description of branches, you learned that branches can be used for development of a new part of a project, separate from the stable version of a repository. A pull request is a way to take a collection of commits on a branch and request to {{< glossary \"merge\">}} those into another {{< glossary \"branch\">}}, typically \"main\". A pull request will provide a list of each file that is changed in the branch, as well as the difference between each file and the version of that file on the branch that you are trying to merge your changes into. While you can review your own pull requests, GitHub also has features that make it convenient for collaborators to review your pull requests. \n\n## How to make a pull request \n***\n\nIn the previous section, you worked locally to make the visualizations that Collab O. Rator had asked you for, and you staged, committed, and pushed these changes. Recall that you were working on a branch called \"study comparison\". Let's take a look at this branch on GitHub. \n\n- [ ] Navigate back to \"https://github.com/your_username/infant_gut_analysis\" (replacing your username). \n- [ ] Click underneath the repository name where is says \"Branches\". This should take you to a page that shows you the existing branches (this should include \"main\" and \"study_comparison\"). \n- [ ] Click on \"study_comparison\". \n- [ ] You should see a yellow banner with a green button that says \"Compare & pull request\". Click on this button. \n\nThis set of steps will bring you to a page where you can make your pull request. The first thing to note is the panel at the top of the page, which gives you the base branch (this will by default be \"main\") and the compare branch (this will be the branch you've been working on, in this case \"study_comparison\"). There is an arrow, showing that you are trying to merge the updates that you've made in the compare branch into the base branch. \n\nThere are a few useful components of this page in which you make a pull request:\n\n1. You have a spot to add a title and a description. \n1. If you scroll down, you'll see a list of commits that make up this pull request along with the commit messages, and a view of each of the files changed/what was changed. \n1. On the right panel next to the title you'll see an option for reviewers. If other users have access to this repository, then you can add them as a reviewer. Depending on how they have configured their notification preferences, they may get an email notification that you've requested a review from them. It is good practice for you to also reach out to them and send them the link to your pull request to review! \n\n### Components of a good pull title and description \n\n- A concise but descriptive title.\n- A description of the changes you want to merge. This is a good place to list files added and modified and give a quick description of those changes. Give plenty of context; you've likely been thinking about the code you want to merge more recently than your collaborator who will review it. \n  - One good way to describe changes is in a checklist of what you've done.\n  - It can also be helpful to include a checklist of what is left to do, especially if your pull request is a work in progress.\n- A request for code review (make specific requests: do you want your collaborator to review all changes? do you want them to focus on a specific file or part of an analysis? do you just a bigger picture review to see if your approach to the problem makes sense?).\n\nFor additional suggestions on making good pull requests, you can read more in [this reproducibility course](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/engaging-in-code-review---as-an-author.html). Also see [this real-world example of a pull request](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/741) with these components, followed by back-and-forth between the author and reviewer to iterate on the proposed changes to the analysis. \n\nAdd a title and a description for your pull request now. \n\n<details>\n<summary>Example pull request for this analysis</summary>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f2d5a3e170_0_164.png){fig-align='center' fig-alt='Example pull request' width=1250}\n:::\n:::\n\n\n</details>\n\n## Merging or closing pull requests \n***\n\nOnce you have created a pull request, it is considered an \"open\" pull request and there are two potential actions, either merging it or closing it. \n\n### Merging pull requests \n\nLet's say that you submitted a pull request, you or your collaborator has decided that the changes look good, and you want to integrate the changes from your development branch into the base branch. This is called \"merging\" your pull request. In most cases, you will see a box that says \"No conflicts with base branch\", and you can click the button that says \"Merge pull request\". However, in some cases, you will not be able to merge until you resolve merge conflicts. See the [troubleshooting section](https://www.opencasestudies.org/ocs-bio-version-control/#troubleshooting-git-and-github) for more information about merge conflicts and how to resolve them. \n\n### Closing pull requests\n\nIf you close a pull request without merging it, this means that you've decided not to integrate the changes from the compare branch into the base branch. This may happen if you decide to go in another direction with an analysis. You can close a pull request by clicking the \"Close pull request\" button at the bottom of the pull request page. It is important to close pull requests that are no longer active so that the set of open pull requests accurately represents the current state of the project. \n\n## Additional notes on pull requests \n***\n\nWhile your pull request is open, any additional changes that you commit and push to this branch will be automatically added to the pull request. \n\nIt is recommended to not let your pull requests get too large. A pull request should be a set of changes that address a certain component of an analysis. Try to avoid combining multiple parts of a project in a single pull request. If you decide to start working on a different part of a project, you can create a new branch for this, and eventually submit a new pull request from that branch. This is a great way to stay organized for complex projects that have different components happening in parallel. Additionally, using more branches and smaller pull requests, each focused on a single set of related changes, can make it easier to review the pull requests and to identify where changes were introduced to a project. \n\n***\n\n# **Summary**\n***\n\n## **Synopsis**\n***\n\n\nIn this case study, you've learned about why {{< glossary \"version control\">}} is used as part of {{< glossary \"reproducible\">}} science workflows. You've been introduced to {{< glossary \"Git\">}} and {{< glossary \"GitHub\">}}, and learned procedures for managing Git-tracked {{< glossary \"repositories\">}} locally using {{< glossary \"GitHub Desktop\">}} or the {{< glossary \"command line\">}}, and remotely using GitHub (github.com). You've practiced using the \"pull -> stage -> commit -> push\" workflow to make changes locally that are then tracked remotely. In your analysis, you worked in a {{< glossary \"branch\">}}, and you submitted a {{< glossary \"pull request\">}} in order to integrate new changes into a stable version of the code and as a way to ask a collaborator to review your code. \n\nAlong the way, you've also learned about the advantages and challenges of {{< glossary \"meta-analyses\">}} and best practices for scientific project organization. \n\n\n## **Summary Activity**\n***\n\n\n### Reconstruct the workflow\n\nDrag each workflow block into the correct position below and click **Check Answer** or **Reset** to start over. This diagram provides a high-level overview of the steps that you took in this case study. While some of these will not always be necessary for all projects or follow this exact order, each of these steps represent parts of a version controlled project workflow and are important to understand. \n\n```{=html}\n<!-- html part of code, creates structure of activity -->\n<!-- creates board with dropzones, arrows, and empty placeholder divs -->\n<div class=\"workflow-wrapper\">\n  <div class=\"workflow-grid\">\n  \n    <!-- Row 1 -->\n    <div class=\"dropzone\" data-correct=\"receive-files\"></div>\n  \n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 100 40\" width=\"60\" height=\"24\">\n        <line x1=\"5\" y1=\"20\" x2=\"80\" y2=\"20\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"80,5 98,20 80,35\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div class=\"dropzone\" data-correct=\"local-git\"></div>\n  \n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 100 40\" width=\"60\" height=\"24\">\n        <line x1=\"5\" y1=\"20\" x2=\"80\" y2=\"20\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"80,5 98,20 80,35\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div class=\"dropzone\" data-correct=\"remote-github\"></div>\n  \n    <!-- Row 2 -->\n    <div></div>\n    <div></div>\n    <div></div>\n  \n    <div class=\"arrow top-down-arrow\">\n      <svg viewBox=\"0 0 40 100\" width=\"20\" height=\"50\">\n        <line x1=\"20\" y1=\"5\" x2=\"20\" y2=\"80\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"5,80 20,98 35,80\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div></div>\n  \n    <!-- Row 3 -->\n    <div class=\"dropzone\" data-correct=\"readme\"></div>\n  \n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 100 40\" width=\"60\" height=\"24\">\n        <line x1=\"95\" y1=\"20\" x2=\"20\" y2=\"20\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"20,5 2,20 20,35\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div class=\"dropzone\" data-correct=\"perform-analysis\"></div>\n  \n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 100 40\" width=\"60\" height=\"24\">\n        <line x1=\"95\" y1=\"20\" x2=\"20\" y2=\"20\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"20,5 2,20 20,35\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div class=\"dropzone\" data-correct=\"make-branch\"></div>\n  \n    <!-- Row 4 -->\n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 40 100\" width=\"20\" height=\"50\">\n        <line x1=\"20\" y1=\"5\" x2=\"20\" y2=\"80\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"5,80 20,98 35,80\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div></div>\n    <div></div>\n    <div></div>\n    <div></div>\n  \n    <!-- Row 5 -->\n    <div class=\"dropzone\" data-correct=\"push-remote\"></div>\n  \n    <div class=\"arrow\">\n      <svg viewBox=\"0 0 100 40\" width=\"60\" height=\"24\">\n        <line x1=\"5\" y1=\"20\" x2=\"80\" y2=\"20\"\n              stroke=\"black\"\n              stroke-width=\"6\"\n              stroke-linecap=\"round\"/>\n        <polygon points=\"80,5 98,20 80,35\"\n                 fill=\"black\"/>\n      </svg>\n    </div>\n  \n    <div class=\"dropzone\" data-correct=\"pull-request\"></div>\n  \n  </div>\n  \n  <!-- creates empty card bank, to be filled with shuffled cards -->\n  <div id=\"bank\" class=\"bank\"></div>\n  \n  <br>\n  \n  <!-- creates buttons to check answer and reset board -->\n  <button id=\"check-btn\">Check Answer</button>\n  <button id=\"reset-btn\">Reset</button>\n  \n  <div id=\"feedback\"></div>\n</div>\n\n<!-- JavaScript part of code, creates interactive features -->\n<!-- calls external library SortableJS to do drag-and-drop interaction -->\n<script src=\"https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js\"></script>\n\n<script>\n\n// create cards, each with an id and a relative path to an image\nconst cards = [\n  { id: \"receive-files\", img: \"img/receive-files.png\" },\n  { id: \"local-git\", img: \"img/local-git.png\" },\n  { id: \"remote-github\", img: \"img/remote-github.png\" },\n  { id: \"make-branch\", img: \"img/make-branch.png\" },\n  { id: \"perform-analysis\", img: \"img/perform-analysis.png\" },\n  { id: \"readme\", img: \"img/readme.png\" },\n  { id: \"push-remote\", img: \"img/push-remote.png\" },\n  { id: \"pull-request\", img: \"img/pull-request.png\" }\n];\n\n// function to shuffle the cards when they are put into the card bank \nfunction shuffle(array) {\n  for (let i = array.length - 1; i > 0; i--) {\n    const j = Math.floor(Math.random() * (i + 1));\n    [array[i], array[j]] = [array[j], array[i]];\n  }\n}\n\n// function to create card \nfunction createCard(card) {\n\n  const div = document.createElement(\"div\");\n\n  div.className = \"card\";\n  div.dataset.id = card.id;\n\n  const img = document.createElement(\"img\");\n\n  img.src = card.img;\n  img.alt = card.id;\n  \n  div.appendChild(img);\n\n  return div;\n}\n\n// function to reset all elements, shuffle cards in bank and clear dropzones \nfunction setupBoard() {\n\n  const bank = document.getElementById(\"bank\");\n\n  bank.innerHTML = \"\";\n\n  document\n    .querySelectorAll(\".dropzone\")\n    .forEach(z => {\n      z.innerHTML = \"\";\n      z.classList.remove(\n        \"correct\",\n        \"incorrect\"\n      );\n    });\n\n  const shuffled = [...cards];\n\n  shuffle(shuffled);\n\n  shuffled.forEach(card => {\n    bank.appendChild(createCard(card));\n  });\n\n}\n\n// initialize drag-and-drop \nwindow.addEventListener(\"load\", function() {\n\n  setupBoard();\n\n  Sortable.create(\n    document.getElementById(\"bank\"),\n    {\n      group: \"workflow\",\n      animation: 150\n    }\n  );\n\n  document\n    .querySelectorAll(\".dropzone\")\n    .forEach(zone => {\n\n      Sortable.create(zone, {\n        group: \"workflow\",\n        animation: 150,\n        \n        onAdd(event) {\n\n          const zone = event.to;\n      \n          if (zone.children.length > 1) {\n      \n            document\n              .getElementById(\"bank\")\n              .appendChild(zone.firstElementChild);\n      \n          }\n        }\n      });\n    });\n});\n\n// event handler, to check all dropzones to see if correct or incorrect \ndocument\n.getElementById(\"check-btn\")\n.addEventListener(\"click\", () => {\n\n  let correct = 0;\n\n  const zones =\n    document.querySelectorAll(\".dropzone\");\n\n  zones.forEach(zone => {\n\n    zone.classList.remove(\n      \"correct\",\n      \"incorrect\"\n    );\n\n    const card =\n      zone.querySelector(\".card\");\n\n    if(!card) {\n\n      zone.classList.add(\"incorrect\");\n      return;\n\n    }\n\n    if(\n      card.dataset.id ===\n      zone.dataset.correct\n    ) {\n\n      correct++;\n      zone.classList.add(\"correct\");\n\n    } else {\n\n      zone.classList.add(\"incorrect\");\n\n    }\n\n  });\n\n  const feedback =\n    document.getElementById(\"feedback\");\n\n  const total = cards.length;\n  \n  if (correct === total) {\n    feedback.innerHTML = \"<p class='pass'>Perfect! All \" + total +\n      \" positions are correct.</p>\";\n  } else {\n    feedback.innerHTML =\n      \"<p class='fail'>\" + correct + \"/\" + total +\n      \" positions are correct. Continue adjusting the workflow.</p>\";\n  }\n\n});\n\n// event handler, to reset the board \ndocument\n.getElementById(\"reset-btn\")\n.addEventListener(\"click\", () => {\n\n  document\n    .getElementById(\"feedback\")\n    .innerHTML = \"\";\n\n  setupBoard();\n\n});\n\n</script>\n\n<!-- CSS part of code, controls layout and style -->\n<style>\n\n/* Make whole workflow scrollable \n.workflow-wrapper {\n  overflow-x: auto;\n  width: 100%;\n} */\n\n/* Set up dimensions of cards and images */\n:root {\n  --card-width: 180px;\n  --card-height: 130px;\n}\n\n/* Set up workflow layout with grid */\n.workflow-grid {\n\n  display: grid;\n\n  grid-template-columns:\n    var(--card-width) 40px var(--card-width) 40px var(--card-width);\n\n  gap: 16px;\n\n  align-items: center;\n  justify-content: center;\n\n  margin-bottom: 40px;\n}\n\n.dropzone {\n\n  width: var(--card-width);\n  height: var(--card-height);\n\n  border: 3px dashed #bdbdbd;\n  border-radius: 12px;\n\n  background: #fafafa;\n\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n\n/* Create arrows */\n.arrow {\n\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n\n.top-down-arrow {\n  transform: translateX(135px);\n}\n\n/* Set up layout of card bank */\n.bank {\n\n  display: grid;\n\n  grid-template-columns:\n    repeat(4, var(--card-width));\n\n  gap: 12px;\n\n  justify-content: center;\n\n  margin-top: 20px;\n}\n\n/* Set up each card */\n.card {\n\n  width: var(--card-width);\n  height: var(--card-height);\n\n  border: none;\n  border-radius: 0;\n\n  background: transparent;\n\n  overflow: hidden;\n\n  cursor: grab;\n}\n\n/* Control how image will look within card */\n.card img {\n\n  width: 95%;\n  height: 95%;\n\n  object-fit: contain;\n  \n  display: block;\n  margin: auto;\n}\n\n/* Style for correct boxes after checking */\n.correct {\n\n  border: 4px solid #26734d;\n  background: #eef8f1;\n}\n\n/* Style for incorrect boxes after checking */\n.incorrect {\n\n  border: 4px solid #b22222;\n  background: #fff0f0;\n}\n\n/* Style if all cards are in correct order */\n.pass {\n\n  color: #26734d;\n  font-weight: 700;\n  font-size: 1.2rem;\n}\n\n/* Style if some cards in incorrect order */\n.fail {\n\n  color: #b22222;\n  font-weight: 700;\n  font-size: 1.2rem;\n}\n\n/* Style for buttons to check answers and reset board */\nbutton {\n\n  padding: 10px 20px;\n  margin-right: 10px;\n  font-size: 1rem;\n}\n\n#feedback {\n\n  margin-top: 20px;\n}\n\n</style>\n\n```\n\n## **Summary Image**\n***\n\nNow that you've reconstructed the version control workflow from this case study, recall the motivation for version control. Without version control, collaborative scientific projects often involve many emails back and forth, and either a single recent version of the project with no record of its history, or a collection of files representing older versions of the project that can be challenging to organize and are not optimal for multiple people to work on. Version control provides a solution to these challenges. When a project is version-controlled, each file within the project has a recorded history, and commits and associated commit messages can be used to understand when and why changes were made. Additionally, version control facilitates collaboration on scientific projects, letting multiple people work on the same set of files more easily, and providing a useful interface for code review through pull requests.  \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f9c5fef626_0_3.png){fig-align='center' fig-alt='Motivation for using version control' width=1250}\n:::\n:::\n\n\n***\n\n\n::: {.content-hidden unless-meta=\"include-sections.main-q-table\"}\n\n<!--\nDon't adjust the shortcode or the table header in this file, only the markdown table contents\n-->\n\n## **Main Questions Revisited**\n\n::: {.callout-note collapse=\"true\" title=\"Main Questions Revisited: What Did We Learn\"}\n\n\n| Question                                    | Current answer                                     | Caveat                                |\n| :------------------------------------------ | :------------------------------------------------- |:------------------------------------- |\n| How does the use of version control contribute to transparent and reproducible science? | As we describe in the [introduction to Git and GitHub section](https://www.opencasestudies.org/ocs-bio-version-control/#introduction-to-git-and-github), version control provides a full history of a project, showing who made which changes and when. Additionally, commit messages and pull request descriptions explain why changes were made. Version control also provides an easy way to make a public online code repository for a project. | Versions of a project are only tracked when the user manually makes a commit, changes are not automatically tracked. Commit messages and pull request descriptions are only useful when they are concise and meaningful. |\n| How can Git and GitHub be used to facilitate collaboration on a research project? | GitHub provides a central location to store the files for a project, and collaborators can pull changes to their local repository, make updates, and push changes back to the remote repository. An individual can suggest a series of changes through a pull request (see the [pull request section](https://www.opencasestudies.org/ocs-bio-version-control/#pull-requests) for more information), and request a code review from a collaborator before merging the changes into the main branch of the repository. | It is important for collaborators to pull before they begin work locally, otherwise they will likely create merge conflicts (see the [troubleshooting section](https://www.opencasestudies.org/ocs-bio-version-control/#troubleshooting-git-and-github) for advice for working through merge conflicts). The careful use of branches will let collaborators work on different aspects of projects at different times and help organize work to be reviewed in pull requests. More information about branches can be found in the [branches section](https://www.opencasestudies.org/ocs-bio-version-control/#branches).|\n| In this meta-analysis of infant gut microbiome samples, how do the original studies compare in their sampling designs? | From the plots created in the [data visualization section](https://www.opencasestudies.org/ocs-bio-version-control/#data_visualization), we can identify major differences across studies in terms of number of samples, proportion of samples from infants versus mothers, and different times at which samples were collected from infants and from mothers. | As described in the [limitations section](https://www.opencasestudies.org/ocs-bio-version-control/#limitations), the sampling date is measured differently in different studies, and there are other potentially relevant study characteristics that we don't consider in this analysis. |\n\n\n:::\n\n***\n\n\n:::\n\n# **Troubleshooting Git and GitHub**\n***\n\nMost new and experienced users of {{< glossary \"Git\">}} and {{< glossary \"GitHub\">}} will run into problems occasionally. Luckily, {{< glossary \"version control\">}} is designed so that these problems can be solved, it just may take some time to get used to. There are many helpful [resources](https://dangitgit.com/en) online for common Git and GitHub problems, and AI chatbots can provide advice (please see our AI disclaimer below for advice on using AI for version control!). In this section, we will mention a few common Git and GitHub problems and provide solutions. \n\n<details> <summary> I {{< glossary \"commit\" display=\"committed\">}} my work but I made a mistake in my most recent commit message that I would like to fix. </summary>\n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nNavigate to the repository in GitHub Desktop and go to the \"History\" pane. Right-click on the commit, and you should see the option \"Amend Commit...\", click on this option. \n\nIf you have not yet pushed your work, you can then update your commit message and click \"Commit\", and then continue working.\n\nHowever, if you have already pushed your work, then you will need to amend the commit message and then force push. This should only be done carefully, because it will rewrite the commit history of the branch for any other collaborator using that branch. Therefore, it is suggested to only do this for branches that you are working on alone, or to alert your collaborator before performing this operation and having them reset their branch after you force push. \n\n#### Command line\n\nIf you have committed but not yet {{< glossary \"push\" display=\"pushed\">}} your work, you can open the command line and do the following:\n\n:::: {.shell}\n```bash\ngit commit --amend -m \"Corrected commit message\"\n```\n::::\n\nIf you have already pushed your work, you will need to run the previous line, and then push those changes.\n\n:::: {.shell}\n```bash\ngit push --force-with-lease\n```\n::::\n\nThe `--force-with-lease` option will push your change to the remote repository, unless the remote branch has new commits. If there are already new commits, this will fail, to avoid disrupting the version history of other users. If you would like to change the message anyway, you can replace `--force-with-lease` with `--force`. \n\n:::\n\n</details>\n\n<details> \n<summary>I've created a merge conflict. What is this? How do I fix it?</summary>\n\nTypically, Git is able to automatically {{< glossary \"merge\">}} changes from one {{< glossary \"branch\">}} into another. However, a merge conflict happens when there are competing changes between the two branches, and Git needs you to manually decide how to resolve these differences. A merge conflict may arise in a scenario in which you made a branch from main, worked on that branch, and by the time you submit a pull request back to main, someone else has already committed to main and updated the same file as you have. \n\n:::{.definition_box}\n::::{.definition_box_header}\nMerge conflict\n::::\n::::{.inner_block}\nWhen Git cannot automatically reconcile differences between branches it is attempting to combine, typically because the same part of a file (or closely related parts) were edited in incompatible ways, or because one branch modified something the other removed.\n::::\n:::\n\nYou will know that you have a merge conflict when Git attempts to combine changes (for example, during `git merge` or `git pull`) and reports that it cannot automatically resolve some differences. \n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nYou will see a pop-up window that says \"Resolve conflicts before Merge\", along with a list of files with conflicts. You will need to open the files in a text editor in order to manually resolve the merge conflicts. \n\n#### Command line\n\nWhen you try to run `git pull`, you'll get a response that includes: \"Automatic merge failed; fix conflicts and then commit the result\". \n\n:::\n\nRecall the hypothetical branch workflow from earlier in the case study.\n\n::: {.panel-tabset}\n#### Step 1\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_733.png){fig-alt='branch workflow: start with Main branch' width=100%}\n:::\n:::\n\n\n#### Step 2\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_774.png){fig-alt='branch workflow: add Plotting branch' width=100%}\n:::\n:::\n\n\n#### Step 3\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_796.png){fig-alt='branch workflow: Commit to Plotting branch' width=100%}\n:::\n:::\n\n\n#### Step 4\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_818.png){fig-alt='branch workflow: Separately, commit to main branch' width=100%}\n:::\n:::\n\n\n#### Step 5\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_840.png){fig-alt='branch workflow: merge Plotting back into Main' width=100%}\n:::\n:::\n\n\n:::\n\nHere is an example of a file from the branching workflow that will result in a merge conflict. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html//1QjS4NwVgB_oZX5YCHKCzVe9x4XRWhNv-N7iP26JXHXo_g3f9c55c112a_0_874.png){fig-alt='file before and after merge conflict' width=100%}\n:::\n:::\n\n\nWhen you open a file with a merge conflict, you will see that conflict markers have been added. For lines that are in conflict, you'll see \"<<<<<<< HEAD\" and \"=======\". The code in between these two markers is the code that is contained locally in the branch that you are working with. Lower in the file, you'll see \">>>>>>> incoming_change_tag\", where \"incoming_change_tag\" references the commit or branch that identifies the incoming change. You need to manually edit the file to remove the tags, and to include whatever content you would like (either the content in your local branch, the content from the remote commit that is being pulled, or a combination of the two). Once you've edited this file, you should save and stage the file. \n\nIn some cases (such as when one branch deletes a file and another edits it), you may not see conflict markers inside a file. Instead, you will need to either remove the file if you want it to be deleted, or stage the file if you would like it to be kept. \n\nAfter you resolve and stage all files that had merge conflicts, you should commit these changes. This will resolve your merge conflict. \n\nYou can read more about when you might merge branches versus using a rebase operation to integrate changes in [this article](https://medium.com/@Spritan/merge-vs-rebase-vs-fast-forward-mastering-git-integration-strategies-3ba8e652d93e). \n\n</details>\n\n<details> <summary> I've accidentally been working in the main branch, but I actually want my work to all go into a new branch. How do I switch branches and move this work with me?   </summary>\n\nLuckily, this is an easy problem to resolve!\n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nIf you have made changes locally but **haven't yet committed**, you can do the following: \n\nOpen GitHub Desktop, and create a new branch. If you have changes in main that haven't been committed, GitHub Desktop will open a pop-up to ask you if you'd like to leave your changes on main or bring your changes to the new branch. Choose to bring the changes to the new branch. \n\nIf you have made changes locally and **have committed**, you can follow the steps above and then additionally do the following: \n\nSwitch back to the main branch, and click on History in the upper left panel. Then, right-click on the commit that you would like to return to in your main branch and choose \"Reset to Commit...\" from the right-click menu.\n\n#### Command line\n\nIf you have made changes locally but haven't yet committed, you can do the following: \n\nUse the following command, replacing \"new_branch_name\" with your desired branch name. \n\n:::: {.shell}\n```bash\ngit checkout -b new_branch_name \n```\n::::\n\nIf you have made changes locally and have committed, you can follow the steps above to create a new branch, and then additionally do the following to revert main back to match the remote version of main: \n\n:::: {.shell}\n```bash\ngit reset --hard origin/main\n```\n::::\n\nHowever, make sure that you only `git reset --hard` after you've created the new branch and moved your commits, otherwise you risk losing your updated work.\n\nAlternately, if you have only edited a few files, you could just run `git restore --hard` for those files. This reverts the files to their previous versions, instead of reverting the full branch. If you have edited files called \"file1.txt\" and \"file2.txt\" and want to revert them to the versions saved in main, you could do the following:\n\n:::: {.shell}\n```bash\ngit fetch origin\ngit restore --source=origin/main file1.txt file2.txt\n```\n::::\n\n\n:::\n\n</details>\n\n<details> <summary> I've staged and committed a file, but I don't want to track it anymore. How can I remove it? </summary>\n\nThis is another common problem. We'll first tell Git to stop tracking the file (but keep it locally), and then we will add it to the .gitignore file to avoid tracking it with Git in the future. First, we will stop tracking the file. \n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nMake sure you are starting in the correct branch that you have been working in. Click \"Repository -> Open in Terminal\". This will open a command line for you to work with. In this command line, use the following command, replacing \"path_to_file\" with the path to the file to stop tracking, including the file name. \n\n:::: {.shell}\n```bash\ngit rm --cached \"path_to_file\" \n```\n::::\n\nNext, open the .gitignore file and add the file to the list of files to avoid tracking. \n\nThen, return to GitHub Desktop and commit these changes. \n\n#### Command line\n\nUse the following command, replacing \"path_to_file\" with the path to the file to stop tracking, including the file name. \n\n:::: {.shell}\n```bash\ngit rm --cached path/to/file\n```\n::::\n\nNext, open the .gitignore file and add the file to the list of files to avoid tracking. \n\nThen, return to the command line and stage and stage and commit these changes. \n\n:::: {.shell}\n```bash\ngit add .gitignore\ngit commit -m \"removing file_name from Git tracking and adding it to .gitignore\" \n```\n::::\n\n:::\n\n</details>\n\n<details> <summary> I've accidentally committed a large file and when I try to push I get an error from GitHub saying that the file is too big. How do I resolve this?  </summary>\n\nThis is a common error that can be a little tricky to resolve. You need to remove this file from Git tracking and also amend the commits that include the file. We will assume that the large file was added in the most recent commit. If it was added multiple commits previously, then it can still be removed but will include additional steps that we will not cover here (see [here](https://www.git-tower.com/learn/git/faq/git-filter-repo) for a workflow for removing a file from multiple commits). \n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nMake sure you are starting in the correct branch that you have been working in. Click \"Repository -> Open in Terminal\". This will open a command line for you to work with. In this command line, use the following command, replacing \"path_to_file\" with the path to the file to stop tracking, including the file name. \n\n:::: {.shell}\n```bash\ngit rm --cached \"path_to_file\" \ngit commit --amend \n```\n::::\n\nIncluding the `git commit --amend` rewrites the most recent commit as if the large file was not added. Don't close the terminal yet, we will come back to it. \n\nNext, open the .gitignore file and add the file to the list of files to avoid tracking. In GitHub Desktop, stage the .gitignore, but do not commit it yet. \n\nReturn to the terminal. Repeat the `git commit --amend` command, which will add this update to the .gitignore to the most recent commit. \n\n:::: {.shell}\n```bash\ngit commit --amend \n```\n::::\n\nThen, return to GitHub Desktop and commit these changes. \n\n#### Command line\n\nUse the following command, replacing \"path_to_file\" with the path to the file to stop tracking, including the file name. Including the `git commit --amend` rewrites the most recent commit as if the large file was not added.\n\n:::: {.shell}\n```bash\ngit rm --cached path/to/file\ngit commit --amend\n```\n::::\n\nNext, open the .gitignore file and add the file to the list of files to avoid tracking. \n\nThen, return to the command line and stage and stage and commit these changes. Note that we include `git commit --amend` a second time to add the changes to the .gitignore file to the previous commit. \n\n:::: {.shell}\n```bash\ngit add .gitignore\ngit commit --amend\ngit commit -m \"removing file_name from Git tracking and adding it to .gitignore\" \n```\n::::\n\n:::\n\nThe best way to avoid this problem is when you add large files to a folder that is tracked with Git, immediately add them to the .gitignore. If you really do want to track them with version control, consider using [Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage) (LFS). \n\n</details>\n\n<details> <summary> I'm in the middle of working on one branch, but I need to pause and make a quick update on another branch. How do I move between branches if I'm not ready to commit my current work? </summary>\n\nThis is a common occurrence when you're working on a project with multiple branches. Imagine that you are deep in work for a feature that you're adding to an analysis, when your collaborator asks you to make a quick update to a different branch that they've been working on. You aren't yet ready to commit the changes that you've been working on. This is a great time to use Git stash! \n\n:::{.panel-tabset}\n#### GitHub Desktop\n\nOpen GitHub Desktop in the current branch that you're working with. In the top toolbar, click \"Branch\" -> \"Stash All Changes\". This will take all of the changes in this branch since your last commit and store them for you to come back to. Once you've done this, you should see no local changes to the branch. You can then move into the other branch you want to work on. \n\nOnce you are ready to return to your original branch and continue your work, navigate back to that branch on GitHub Desktop. In the \"Changes\" panel, you should see the message \"Stashed Changes\". If you click on this, it will bring you to a page where you can click the \"Restore\" button to return your stashed changes to the branch. You can continue working from there. \n\n#### Command line\n\nOpen the command line to the branch that you've been working in. To save the changes in your current branch for you to later return to, use the following command:\n\n:::: {.shell}\n```bash\ngit stash\n```\n::::\n\nAfter doing this, you can move to the other branch that you'd like to work on. Once you are ready to return to your original branch and continue your work, navigate back to that branch, and use the following command:\n\n:::: {.shell}\n```bash\ngit stash pop\n```\n::::\n\nThis command will restore your stashed changes to the current branch.\n\n:::\n\nTo learn more about Git stash and additional options, you can read its [documentation from Git](https://git-scm.com/docs/git-stash).\n\n</details>\n\nYou can learn more about other common Git mistakes and their fixes [in this article](https://www.creative-tim.com/blog/educational-tech/git-tutorial-fix-common-mistakes/).\n\n:::{.ai_box}\n::::{.ai_box_header}\nAI use considerations\n::::\n::::{.inner_block}\n\n<u>Context:</u>\n\nWhen you ask an AI chatbot for assistance with version control, make sure to give appropriate background. Describe the specific task that you would like to do, or the problem that you are encountering. It can be helpful to include any error messages that you might be receiving from Git. For example, imagine that you've created a merge conflict. \n\n<u>Suggested Prompt:</u>\n\n```{ .default .code-overflow-wrap }\nI am working with a Git-controlled repository, in a branch called new_feature. I have made several changes locally, and have staged those files and committed them. I just went to pull changes from the remote version of this branch that my collaborator made recently, and I'm getting a merge conflict. Specifically, I've received the following message:\n\nAuto-merging README.md\nCONFLICT (content): Merge conflict in README.md\nAuto-merging 01_import_data.R\nCONFLICT (content): Merge conflict in 01_import_data.R\nAutomatic merge failed; fix conflicts and then commit the result.\n\nHow can I resolve this merge conflict?\n```\n\n<u>Validation:</u>\nYou should always be careful when taking advice on Git and GitHub from an AI chatbot. If you are asking for commands to use with Git for a situation that is very new to you, it could be helpful to do a quick search of the commands the chatbot tells you to use, to confirm that they do what you want to do. You could also ask multiple chatbots the same question. \n\nYou should be especially careful when using agentic AI with Git and GitHub. Agentic AI systems can use external tools and execute tasks, often performing steps without human supervision. There are many git commands (and command line commands in general) that are challenging to reverse and can cause major problems to scientific projects. For example, running `git reset --hard` will reset a local branch to the remote version of the branch, removing all uncommitted changes, which could remove valuable content. Therefore, it is recommended to monitor the ways that agentic AI can make changes with version control and to prevent them from performing potentially destructive actions without human supervision.\n::::\n:::\n\n***\n\n\n# **Continued Learning**\n***\n\n:::{.next_steps_box}\n::::{.next_steps_box_header}\nCommon Next Steps\n::::\n::::{.inner_block}\nNow that you've learned how to how to make and use version-controlled repositories, you are ready to use Git and GitHub for your work! Common next steps include:\n\n- [adding collaborators to your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/repository-access-and-collaboration/inviting-collaborators-to-a-personal-repository)\n- making more branches for other components of your analysis\n- using [GitHub issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues) to keep track of to-do's related to your GitHub repository \n::::\n:::\n\n## Reinforcement Exercises\n***\n\nA good way to reinforce these version control skills is to make a current scientific project that you've been working on into a Git tracked repository, and connecting it to a remote GitHub repository. See if you can integrate the Git workflow that you've learned here into your scientific process. Even if you are the only one working on this project, this is a good way to practice skills. This will get you into the habit of staging, committing, and pushing changes as you work, and working on different branches for different components of a project. \n\n## Advancement Exercises\n***\n\n### Beginner\n\n#### Moving work in progress into a new branch \n\nIn this exercise, we will follow a process where we start to make changes to the main branch, but then realize that we would rather keep this work in a separate branch and only merge it into the main branch of the repository through a pull request after code review. \n\nComplete the following steps:\n\n- [ ] Open repository for this case study.\n- [ ] Check out the main branch.\n- [ ] Add a new line to the README (add whatever you'd like here!).\n- [ ] Follow the instructions on the [troubleshooting section](https://www.opencasestudies.org/ocs-bio-version-control/#troubleshooting-git-and-github) to move this update to the README to a new branch called updated_readme.\n- [ ] Commit and push your changes to a remote updated_readme branch.\n- [ ] Submit another pull request on GitHub to contribute this change into the main branch. \n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\nWhat are some advantages to making changes to a repository within a new branch and using a pull request to merge these changes into the main branch? \n\n<details><summary>Answer</summary>\n\nThere are several advantages to this workflow: \n\n- Using a new branch lets you try new things without disrupting a stable version of the code and project.\n- Multiple people can work on different components of a project on their own branches, and then merge the branches into main when they are ready to contribute their work.\n- A branch and pull request lets you group several related commits together, and describe in more detail in the pull request why you made them.\n- The \"Files changed\" tab can help you identify exactly which lines were changed across all commits included in the pull requests, which is often more convenient than separately looking at the changes from each commit.\n- A pull request lets you request a code review from a team member or collaborator before merging your work into main, making you less susceptible to mistakes in your analysis.\n\n</details>\n::::\n:::\n\n### Intermediate\n\n#### Going through a project's history \n\nIn this exercise you will search through the history in a GitHub repository to find when a change took place. \nOpen this [GitHub repository](https://github.com/opencasestudies/ocs-bio-version-control) which contains the contents of this case study. Feel free to spend some time poking around here, all of the content that is used to create different components of this case study are stored in this repository. \n\nYour goal is to find the pull request number and commit tag from when the learning objectives map table was filled in within the case study (the learning objectives table can be found [here](https://www.opencasestudies.org/ocs-bio-version-control/#objectives-map)). Do this by searching through the files, commits, or pull requests in this repository. \n\n<details>\n<summary>Hints:</summary>\n\nThere are multiple ways to search for this change:\n\n- Open the file _lo_map.qmd and click the \"History\" button to see a history of commits that affected this file.\n- Go to the \"Pull requests\" tab, click on the \"Closed\" pull requests, and search a relevant search term. Once you find the correct pull request, look at the commits that make up that pull request.   \n\n</details>\n\n<details>\n<summary>Answer:</summary>\n\nContent was added to the learning objectives map in [pull request 18](https://github.com/opencasestudies/ocs-bio-version-control/pull/18), within the commit tagged [34a4550](https://github.com/opencasestudies/ocs-bio-version-control/commit/34a455071ec726470567932402f9496650ec46d6). \n\n</details>\n\n### Advanced\n\n#### Forking\n\nSo far, you've created repositories to work with. This means that GitHub considers you the repository owner. If you are working with collaborators who you want to be able to push to your GitHub repo, you can add them to your repository with write permissions (you can also make them a maintainer or admin to have additional abilities). However, let's consider a different situation. You want to contribute to a GitHub repository, but you do not have permission to push to this repository. This is where forks come in. \n\n:::{.definition_box}\n::::{.definition_box_header}\nFork \n::::\n::::{.inner_block}\nA copy of a repository, often used to make changes when the user does not have write access to the original repository. \n::::\n:::\n\nWe will call the original repository (which you do not have write permissions for) the upstream. Earlier, when you cloned a GitHub repository, you made a local version of that repository. In contrast, when you fork from the upstream, you make a remote copy of the GitHub repository, that you own with your GitHub account. You can then clone this fork, so that you can work locally. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f139628ce6_0_369.png){fig-align='center' fig-alt='Fork workflow, making local repo' width=1250}\n:::\n:::\n\n\nWhen you want to propose changes back to the upstream repository, you can submit a pull request from your fork into the upstream. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html//1TEi1D35oiiC21mYR0cKjWuOOpuxm3fTGyCXSqFmjL3I_g3f139628ce6_0_399.png){fig-align='center' fig-alt='Fork repo, integrating local changes to remote' width=1250}\n:::\n:::\n\n\n##### Practice making and using a fork\n\nTo practice using a fork, go to [this GitHub repository](https://github.com/opencasestudies/version_controlled_infant_gut_analysis). You'll see that this repository contains the files that you originally downloaded when you started working on this infant gut analysis project. \n\nLook for the button that says \"Fork\" on the top right, above the \"Code\" button that you previously used to clone a repository. Click on \"Fork\". \n\nThis will bring you to a page that is very similar to when you had created a new repository at the beginning of the case study. However, there are a few differences. You'll see now that you are the owner of this repository, and by default it has the same name as the repository that you are forking from. Click \"Create fork\". \n\nOnce you create the fork, you'll be brought to this repository. Now, follow the same process that you used previously to clone this repository (*note: make sure that you are cloning the fork, and not the upstream repository!*). Open the repository locally. Make a copy of the file \"03_visualize_study_cohorts.qmd\", and add it to your local version of your forked repo. Follow the workflow to stage this file, commit it, and push it. \n\nAfter you push, you should now see the file on GitHub in your forked repo, along with a notification that this branch is a commit ahead of the upstream repository. There will be a button with the option to \"Contribute\" these changes. Click that button. This will take you to a page on the upstream repository where you can make a pull request from your fork. \n\nFill in the title and description of your pull request. \n\n:::{.think_question}\n::::{.think_question_header}\nQuestion opportunity\n::::\n::::{.inner_block}\n\nHow does this pull request from a fork to an upstream repository look different from the pull request that you made earlier, between two branches in the same repository? How does it look similar? \n\n::::\n:::\n\nClick \"Create pull request\" and inspect your pull request. \n\nFinally, please close this pull request, as we do not actually want to include these changes in this repository. \n\n***\n\n\n# **Additional Information**\n***\n\n<!--\nUse this section to provide any additional information or resources on the topic and methods covered in the case study\n-->\n\n## **Helpful Links**\n***\n\n- [happy git with R](https://happygitwithr.com): online book that covers most relevant topics for using Git and GitHub with R\n- [How to Use Git/GitHub with R](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r): blog post about getting Git and GitHub set up and working with RStudio. This uses the built-in Git GUI in RStudio instead of GitHub Desktop\n- [Dangit, Git!?!](https://dangitgit.com/en): brief description of some common Git errors and how to resolve them\n- [Git Tutorial: How to Fix 18 Common Mistakes](https://www.creative-tim.com/blog/educational-tech/git-tutorial-fix-common-mistakes/): another collection of common Git errors and their fixes\n- [Intro to reproducibility in cancer informatics](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/): short course on reproducibility for scientific projects, includes Git and GitHub in chapter 4 and provides other resources on reproducibility\n- [Advanced reproducibility in cancer informatics](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/): short course on more advanced reproducibility for scientific projects, includes GitHub in chapter 3 and provides other resources on reproducibility\n- [Carpentries](https://carpentries.org):\n  - [Install Git](https://carpentries.github.io/workshop-template/install_instructions/): instructions on installing Git (and other types of software)\n  - [Set up Git](https://swcarpentry.github.io/git-novice/02-setup.html): instructions on setting up Git\n  - [Build on existing branch](https://docs.carpentries.org/resources/curriculum/fetch-existing-branch.html): instructions on how to work from a branch on someone else's fork of a repository \n- [Hands on introduction to Git and GitHub](https://training.arcadiascience.com/workshops/20220920-intro-to-git-and-github/lesson/): another introduction to Git and GitHub, covering some overlapping material and some additional material\n- [Contributing to Galaxy Training Network with GitHub](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/github-contribution/tutorial.html): tutorial on how to contribute to an open source project with GitHub\n- [GitHub cheatsheet](https://education.github.com/git-cheat-sheet-education.pdf): cheatsheet with Git commands that can be used in the command line\n- [Merge vs. Rebase vs. Fast-Forward: Mastering Git Integration Strategies](https://medium.com/@Spritan/merge-vs-rebase-vs-fast-forward-mastering-git-integration-strategies-3ba8e652d93e): article that explains the differences between merging, rebasing, and fast-forwarding, as well as when to use each of them\n\n<!--\nAutomatically include the packages table from _packages.qmd?\n-->\n\n\n\n## Glossary\n\n`````{=html}\n<table class='glossary_table'>\n<tr><th><b>Term</b></th><th><b>Definition</b></th></tr>\n<tr><td>.gitignore</td><td>File that tells Git what files to avoid tracking\n</td></tr>\n<tr><td>branch</td><td>A history of commits in a Git-tracked repository (there can be multiple parallel branches in a repository) \n</td></tr>\n<tr><td>command line</td><td>A window that lets a user interact with a computer through typing commands\n</td></tr>\n<tr><td>commit</td><td>A snapshot of all files in a repository at a moment in time \n</td></tr>\n<tr><td>fork</td><td>A copy of a remote GitHub repository, owned on a personal GitHub account\n</td></tr>\n<tr><td>Git</td><td>A popular version control tool that works to track files on a local computer \n</td></tr>\n<tr><td>Git LFS</td><td>Git large file storage, an option to version control large files that are too large to track using Git and GitHub\n</td></tr>\n<tr><td>GitHub</td><td>A website for hosting folders that are tracked with GitHub\n</td></tr>\n<tr><td>GitHub Desktop</td><td>A graphical user interface for interacting with Git on a local computer \n</td></tr>\n<tr><td>license</td><td>A legal document that states who can use your code and for what purposes \n</td></tr>\n<tr><td>local</td><td>The Git-tracked repository on your computer\n</td></tr>\n<tr><td>longitudinal</td><td>Over time (a longitudinal study follows a group of participants over time)\n</td></tr>\n<tr><td>merge</td><td>Integrating changes from one branch to another branch \n</td></tr>\n<tr><td>merge conflict</td><td>When Git cannot automatically reconcile differences between branches it is attempting to combine, typically because the same part of a file (or closely related parts) were edited in incompatible ways, or because one branch modified something the other removed\n</td></tr>\n<tr><td>meta-analyses</td><td>Analyses of data from a collection of studies targeting a common research question\n</td></tr>\n<tr><td>meta-analysis</td><td>An analysis of data from a collection of studies targeting a common research question\n</td></tr>\n<tr><td>microbiome</td><td>A collection of microorganisms that live in a shared environment\n</td></tr>\n<tr><td>pull request</td><td>A request to integrate a collection of commits from one branch (or from a fork) into another branch (or another repository)\n</td></tr>\n<tr><td>push</td><td>Sending commits from the local version of a repository to the remote version of the repository on GitHub\n</td></tr>\n<tr><td>quarto</td><td>A type of document that combines code with the output of the code and text \n</td></tr>\n<tr><td>README</td><td>A document that describes what files are in a folder, as well as other relevant information \n</td></tr>\n<tr><td>remote</td><td>The online version of the repository tracked on GitHub\n</td></tr>\n<tr><td>repo</td><td>A shortened version of \"repository\", a folder in Git that contains all of hte files to be tracked for a project\n</td></tr>\n<tr><td>repositories</td><td>Folders in Git that contains all of the files to be tracked for a project\n</td></tr>\n<tr><td>repository</td><td>A folder in Git that contains all of the files to be tracked for a project\n</td></tr>\n<tr><td>reproducibility</td><td>The ability for someone else to run the same analysis on the same data and get the same results\n</td></tr>\n<tr><td>reproducible</td><td>A project in which a new researcher can re-run an experiment or analysis with the same data and code and generate the same results\n</td></tr>\n<tr><td>version control</td><td>A tool that records changes to a project over time</td></tr>\n</table>\n`````\n\n\n## References\n***\n\n::: {#refs}\n:::\n\n\n\n## **Session info**\n***\n\n:::{.reproducibility_box}\n::::{.reproducibility_box_header}\nReproducibility considerations\n::::\n::::{.inner_block}\nWhile using version control to track the data and code that produce a given output improves the reproducibility of a project, two people can be working from the same GitHub repository and get different results when they run an identical script. This can happen if they have different versions of the software they are using (for example, different versions of the same R package). To learn more about standardizing the versions of tools to use in an analysis, you can work through this [open case study](https://www.opencasestudies.org/ocs-bio-containers/) about containers. However, a good first step is to print the versions of software that you are using for a project. We do that here, using the R function `session_info()` from the `devtools` package.\n::::\n:::\n\n:::{.rcode}\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.3.2 (2023-10-31)\n os       Ubuntu 22.04.4 LTS\n system   x86_64, linux-gnu\n ui       X11\n language (EN)\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Etc/UTC\n date     2026-09-29\n pandoc   3.1.1 @ /usr/local/bin/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package     * version date (UTC) lib source\n cachem        1.0.8   2023-05-01 [1] RSPM (R 4.3.0)\n cellranger    1.1.0   2016-07-27 [1] RSPM (R 4.3.0)\n chromote      0.5.1   2025-04-24 [1] CRAN (R 4.3.2)\n cli           3.6.5   2025-04-23 [1] CRAN (R 4.3.2)\n colorspace    2.1-0   2023-01-23 [1] RSPM (R 4.3.0)\n curl          7.0.0   2025-08-19 [1] CRAN (R 4.3.2)\n devtools      2.4.5   2022-10-11 [1] RSPM (R 4.3.0)\n digest        0.6.34  2024-01-11 [1] RSPM (R 4.3.0)\n dplyr       * 1.1.4   2023-11-17 [1] RSPM (R 4.3.0)\n ellipsis      0.3.2   2021-04-29 [1] RSPM (R 4.3.0)\n evaluate      1.0.5   2025-08-27 [1] CRAN (R 4.3.2)\n fansi         1.0.6   2023-12-08 [1] RSPM (R 4.3.0)\n farver        2.1.1   2022-07-06 [1] RSPM (R 4.3.0)\n fastmap       1.1.1   2023-02-24 [1] RSPM (R 4.3.0)\n fs            1.6.3   2023-07-20 [1] RSPM (R 4.3.0)\n generics      0.1.3   2022-07-05 [1] RSPM (R 4.3.0)\n ggplot2     * 3.5.0   2024-02-23 [1] RSPM (R 4.3.0)\n gitcreds      0.1.2   2022-09-08 [1] RSPM (R 4.3.0)\n glue          1.7.0   2024-01-09 [1] RSPM (R 4.3.0)\n gtable        0.3.4   2023-08-21 [1] RSPM (R 4.3.0)\n here        * 1.0.2   2025-09-15 [1] CRAN (R 4.3.2)\n hms           1.1.3   2023-03-21 [1] RSPM (R 4.3.0)\n htmltools     0.5.7   2023-11-03 [1] RSPM (R 4.3.0)\n htmlwidgets   1.6.4   2023-12-06 [1] RSPM (R 4.3.0)\n httpuv        1.6.14  2024-01-26 [1] RSPM (R 4.3.0)\n httr          1.4.7   2023-08-15 [1] RSPM (R 4.3.0)\n jsonlite      2.0.0   2025-03-27 [1] CRAN (R 4.3.2)\n knitr         1.50    2025-03-16 [1] CRAN (R 4.3.2)\n labeling      0.4.3   2023-08-29 [1] RSPM (R 4.3.0)\n later         1.3.2   2023-12-06 [1] RSPM (R 4.3.0)\n lifecycle     1.0.4   2023-11-07 [1] RSPM (R 4.3.0)\n magrittr      2.0.3   2022-03-30 [1] RSPM (R 4.3.0)\n memoise       2.0.1   2021-11-26 [1] RSPM (R 4.3.0)\n mime          0.12    2021-09-28 [1] RSPM (R 4.3.0)\n miniUI        0.1.1.1 2018-05-18 [1] RSPM (R 4.3.0)\n munsell       0.5.0   2018-06-12 [1] RSPM (R 4.3.0)\n ottrpal       2.0.0   2025-12-16 [1] Github (ottrproject/ottrpal@6d1267e)\n pillar        1.9.0   2023-03-22 [1] RSPM (R 4.3.0)\n pkgbuild      1.4.3   2023-12-10 [1] RSPM (R 4.3.0)\n pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 4.3.0)\n pkgload       1.4.1   2025-09-23 [1] CRAN (R 4.3.2)\n png           0.1-8   2022-11-29 [1] CRAN (R 4.3.2)\n processx      3.8.6   2025-02-21 [1] CRAN (R 4.3.2)\n profvis       0.3.8   2023-05-02 [1] RSPM (R 4.3.0)\n promises      1.2.1   2023-08-10 [1] RSPM (R 4.3.0)\n ps            1.9.1   2025-04-12 [1] CRAN (R 4.3.2)\n purrr         1.0.2   2023-08-10 [1] RSPM (R 4.3.0)\n R6            2.6.1   2025-02-15 [1] CRAN (R 4.3.2)\n Rcpp          1.0.12  2024-01-09 [1] RSPM (R 4.3.0)\n readr         2.1.5   2024-01-10 [1] RSPM (R 4.3.0)\n readxl      * 1.4.3   2023-07-06 [1] RSPM (R 4.3.0)\n remotes       2.4.2.1 2023-07-18 [1] RSPM (R 4.3.0)\n rlang         1.1.6   2025-04-11 [1] CRAN (R 4.3.2)\n rmarkdown     2.25    2023-09-18 [1] RSPM (R 4.3.0)\n rprojroot     2.1.1   2025-08-26 [1] CRAN (R 4.3.2)\n rvest         1.0.5   2025-08-29 [1] CRAN (R 4.3.2)\n scales        1.3.0   2023-11-28 [1] RSPM (R 4.3.0)\n sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.3.0)\n shiny         1.8.0   2023-11-17 [1] RSPM (R 4.3.0)\n spelling      2.3.2   2025-08-18 [1] CRAN (R 4.3.2)\n stringi       1.8.3   2023-12-11 [1] RSPM (R 4.3.0)\n stringr     * 1.5.1   2023-11-14 [1] RSPM (R 4.3.0)\n tibble        3.3.0   2025-06-08 [1] CRAN (R 4.3.2)\n tidyr         1.3.1   2024-01-24 [1] RSPM (R 4.3.0)\n tidyselect    1.2.0   2022-10-10 [1] RSPM (R 4.3.0)\n tzdb          0.4.0   2023-05-12 [1] RSPM (R 4.3.0)\n urlchecker    1.0.1   2021-11-30 [1] RSPM (R 4.3.0)\n usethis       2.2.3   2024-02-19 [1] RSPM (R 4.3.0)\n utf8          1.2.4   2023-10-22 [1] RSPM (R 4.3.0)\n vctrs         0.6.5   2023-12-01 [1] RSPM (R 4.3.0)\n viridisLite   0.4.2   2023-05-02 [1] RSPM (R 4.3.0)\n webshot2      0.1.2   2025-04-23 [1] CRAN (R 4.3.2)\n websocket     1.4.4   2025-04-10 [1] CRAN (R 4.3.2)\n withr         3.0.2   2024-10-28 [1] CRAN (R 4.3.2)\n xfun          0.55    2025-12-16 [1] CRAN (R 4.3.2)\n xml2          1.5.1   2025-12-01 [1] CRAN (R 4.3.2)\n xtable        1.8-4   2019-04-21 [1] RSPM (R 4.3.0)\n yaml        * 2.3.12  2025-12-10 [1] CRAN (R 4.3.2)\n\n [1] /usr/local/lib/R/site-library\n [2] /usr/local/lib/R/library\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n:::\n\n\n\n## **Acknowledgments**\n***\n\n<!--\nFill in any Acknowledgments using an example from a previous case study if needed: https://www.opencasestudies.org/ocs-bp-co2-emissions/#Acknowledgments\n-->\n\nWe would like to acknowledge [Candace Savonen](https://www.cansavvy.com), [Casey Greene](https://greenelab.com/members/casey-greene.html), [Emma Lathouwers](https://greenelab.com/members/emma-lathouwers.html), and [Taylor Reiter](https://taylorreiter.github.io) for their expert review of this case study. \n\nWe would also like to acknowledge the National Institute of General Medical Sciences for funding this work (1R25GM160622).\n\nIcons are from [iconpacks](https://www.iconpacks.net/).\n\nAvatars are from [avataaars](https://getavataaars.com)\n\n\n### AI Attribution Statement\n\n\nThe text in this work was primarily human-created. AI was used to make content edits, such as changes to scope, information, and ideas. AI was prompted for its contributions. AI-generated content was reviewed and approved. The following model(s) or application(s) were used: Microsoft 356 Copilot (GPT-5).\n\nAIA Primarily human, Content edits, Human-initiated, Reviewed, Microsoft 356 Copilot (GPT-5) v1.0\n\nThe code for the drag-and-drop activity was entirely AI-generated. AI was prompted for its contributions. AI-generated content was reviewed and approved. The following model(s) or application(s) were used: Microsoft 356 Copilot (GPT-5).\n\nAIA Entirely AI, Human-initiated, Reviewed, Microsoft 356 Copilot (GPT-5) v1.0\n\nMore information about this AI attribution can be found [here](https://aiattribution.github.io).\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}